import type { Locale } from "./config";

export type ToolSlug =
  | "pdf/merge"
  | "pdf/split"
  | "pdf/compress"
  | "pdf/to-image"
  | "pdf/image-to-pdf"
  | "pdf/add-watermark"
  | "pdf/rotate"
  | "pdf/extract-text"
  | "pdf/reorder"
  | "image/compress"
  | "image/resize"
  | "image/crop"
  | "image/convert"
  | "image/add-watermark"
  | "text/char-count"
  | "text/case-convert"
  | "text/duplicate"
  | "text/diff"
  | "text/regex"
  | "unit/length"
  | "unit/weight"
  | "unit/temperature"
  | "unit/area"
  | "unit/volume"
  | "unit/speed"
  | "unit/data"
  | "unit/time"
  | "color/picker"
  | "color/hex-rgb"
  | "color/palette"
  | "crypto/hash"
  | "crypto/base64"
  | "crypto/url-encode"
  | "crypto/uuid"
  | "dev/json-format"
  | "dev/timestamp"
  | "dev/qrcode"
  | "dev/password"
  | "pdf/page-numbers"
  | "pdf/sign"
  | "pdf/metadata"
  | "pdf/header-footer"
  | "pdf/compare"
  | "pdf/cropPdf"
  | "image/rotate"
  | "image/flip"
  | "image/base64"
  | "image/exif"
  | "image/blur"
  | "image/upscale"
  | "image/meme"
  | "text/reverse"
  | "text/sort"
  | "text/lorem"
  | "text/markdown"
  | "text/fancy"
  | "text/rot13"
  | "unit/pressure"
  | "unit/energy"
  | "unit/power"
  | "unit/fuel"
  | "color/gradient"
  | "color/contrast"
  | "color/mixer"
  | "color/named"
  | "crypto/jwt"
  | "crypto/hmac"
  | "crypto/checksum"
  | "dev/yamlJson"
  | "dev/csv"
  | "dev/sql"
  | "dev/xml";

export type Tool = {
  slug: ToolSlug;
  category: "pdf" | "image" | "text" | "unit" | "color" | "crypto" | "dev";
  icon: string;
  name: Record<Locale, string>;
  description: Record<Locale, string>;
  /** FAQ: each entry is { question, answer } localized for all 7 languages */
  faq?: Array<{ question: Record<Locale, string>; answer: Record<Locale, string> }>;
};

// 工具图标用 lucide-react 名字
export const tools: Tool[] = [
  // PDF
  {
    slug: "pdf/merge", category: "pdf", icon: "Combine",
    name: { en: "Merge PDF", zh: "合并 PDF", ja: "PDF 結合", es: "Combinar PDF", pt: "Mesclar PDF", fr: "Fusionner PDF", de: "PDF zusammenführen" },
    description: { en: "Combine multiple PDF files into one", zh: "将多个 PDF 合并为一个", ja: "複数の PDF を 1 つに結合", es: "Combinar varios PDF en uno", pt: "Combine vários PDFs em um", fr: "Combinez plusieurs PDF en un", de: "Mehrere PDFs in einer Datei kombinieren" },
    faq: [
      { question: { en: "Is the PDF merge tool free?", zh: "PDF 合并工具免费吗？", ja: "PDF 結合ツールは無料ですか？", es: "¿La herramienta de fusión de PDF es gratuita?", pt: "A ferramenta de mesclagem de PDF é gratuita?", fr: "L'outil de fusion PDF est-il gratuit ?", de: "Ist das PDF-Zusammenführungs-Tool kostenlos?" }, answer: { en: "Yes, completely free. No signup, no watermark, no file limits.", zh: "完全免费。无需注册，无水印，无文件限制。", ja: "はい、完全無料。登録不要、透かしなし、ファイル制限なし。", es: "Sí, totalmente gratis. Sin registro, sin marca de agua, sin límite de archivos.", pt: "Sim, totalmente gratuito. Sem cadastro, sem marca d'água, sem limites de arquivo.", fr: "Oui, totalement gratuit. Pas d'inscription, pas de filigrane, pas de limite de fichiers.", de: "Ja, völlig kostenlos. Keine Registrierung, kein Wasserzeichen, keine Dateibeschränkungen." } },
      { question: { en: "Are my PDF files uploaded to a server?", zh: "我的 PDF 文件会上传到服务器吗？", ja: "PDF ファイルはサーバーにアップロードされますか？", es: "¿Mis archivos PDF se suben a un servidor?", pt: "Meus arquivos PDF são enviados para um servidor?", fr: "Mes fichiers PDF sont-ils téléchargés sur un serveur ?", de: "Werden meine PDF-Dateien auf einen Server hochgeladen?" }, answer: { en: "No. All merging happens in your browser using pdf-lib. Your files never leave your device.", zh: "不会。所有合并操作在您的浏览器中通过 pdf-lib 完成，文件不会离开您的设备。", ja: "いいえ、すべての結合は pdf-lib を使ってブラウザ内で行われ、ファイルがデバイスを離れることはありません。", es: "No. Toda la fusión ocurre en tu navegador usando pdf-lib. Tus archivos nunca salen de tu dispositivo.", pt: "Não. Toda a mesclagem acontece no seu navegador usando pdf-lib. Seus arquivos nunca saem do seu dispositivo.", fr: "Non. Toute la fusion se fait dans votre navigateur via pdf-lib. Vos fichiers ne quittent jamais votre appareil.", de: "Nein. Das Zusammenführen erfolgt im Browser mit pdf-lib. Ihre Dateien verlassen Ihr Gerät nie." } },
      { question: { en: "Is there a limit on how many PDFs I can merge?", zh: "可以合并的 PDF 数量有上限吗？", ja: "結合できる PDF の数に上限はありますか？", es: "¿Hay un límite en la cantidad de PDFs que puedo combinar?", pt: "Há um limite de quantos PDFs posso mesclar?", fr: "Y a-t-il une limite au nombre de PDF que je peux fusionner ?", de: "Gibt es eine Begrenzung für die Anzahl der PDFs, die ich zusammenführen kann?" }, answer: { en: "No hard limit, but very large files may be slow due to browser memory.", zh: "没有硬性限制，但非常大的文件可能因浏览器内存变慢。", ja: "厳密な上限はありませんが、非常に大きなファイルはブラウザメモリの関係で遅くなる場合があります。", es: "Sin límite estricto, pero archivos muy grandes pueden ser lentos por la memoria del navegador.", pt: "Sem limite rígido, mas arquivos muito grandes podem ficar lentos devido à memória do navegador.", fr: "Pas de limite stricte, mais les très gros fichiers peuvent être lents à cause de la mémoire du navigateur.", de: "Keine harte Grenze, aber sehr große Dateien können wegen des Browser-Speichers langsam sein." } },
    ]
  },
  {
    slug: "pdf/split", category: "pdf", icon: "Scissors",
    name: { en: "Split PDF", zh: "分割 PDF", ja: "PDF 分割", es: "Dividir PDF", pt: "Dividir PDF", fr: "Diviser PDF", de: "PDF teilen" },
    description: { en: "Split PDF into separate pages or ranges", zh: "将 PDF 拆分为单独页面或范围", ja: "PDF を個別のページまたは範囲に分割", es: "Dividir PDF en páginas o rangos separados", pt: "Dividir PDF em páginas ou intervalos separados", fr: "Diviser un PDF en pages séparées", de: "PDF in separate Seiten oder Bereiche aufteilen" },
    faq: [
      { question: { en: "How do I split specific pages?", zh: "如何分割指定页面？", ja: "特定のページを分割するには？", es: "¿Cómo divido páginas específicas?", pt: "Como divido páginas específicas?", fr: "Comment diviser des pages spécifiques ?", de: "Wie teile ich bestimmte Seiten?" }, answer: { en: "Use the 'Custom range' mode and enter ranges like '1-3, 5, 7-9' to extract exactly those pages into a new PDF.", zh: "使用'自定义范围'模式，输入类似 '1-3, 5, 7-9' 这样的范围即可将这些页提取为新 PDF。", ja: "「カスタム範囲」モードを使い、「1-3, 5, 7-9」のような範囲を入力すると、そのページだけを新しい PDF に抽出できます。", es: "Usa el modo 'Rango personalizado' e ingresa rangos como '1-3, 5, 7-9' para extraer exactamente esas páginas en un nuevo PDF.", pt: "Use o modo 'Intervalo personalizado' e insira intervalos como '1-3, 5, 7-9' para extrair exatamente essas páginas em um novo PDF.", fr: "Utilisez le mode 'Plage personnalisée' et entrez des plages comme '1-3, 5, 7-9' pour extraire exactement ces pages dans un nouveau PDF.", de: "Verwenden Sie den Modus 'Benutzerdefinierter Bereich' und geben Sie Bereiche wie '1-3, 5, 7-9' ein, um genau diese Seiten in eine neue PDF zu extrahieren." } },
      { question: { en: "Can I split a PDF into individual pages?", zh: "可以把 PDF 拆分成单独的页面吗？", ja: "PDF を 1 ページずつに分割できますか？", es: "¿Puedo dividir un PDF en páginas individuales?", pt: "Posso dividir um PDF em páginas individuais?", fr: "Puis-je diviser un PDF en pages individuelles ?", de: "Kann ich ein PDF in einzelne Seiten aufteilen?" }, answer: { en: "Yes. Use the 'One page per file' mode and each page becomes a separate PDF download.", zh: "可以。使用'每页一文件'模式，每页会成为单独的 PDF 下载。", ja: "はい。「1 ページずつファイル」モードを使うと、各ページが個別の PDF としてダウンロードされます。", es: "Sí. Usa el modo 'Una página por archivo' y cada página se descargará como un PDF separado.", pt: "Sim. Use o modo 'Uma página por arquivo' e cada página se tornará um download de PDF separado.", fr: "Oui. Utilisez le mode 'Une page par fichier' et chaque page devient un téléchargement PDF séparé.", de: "Ja. Verwenden Sie den Modus 'Eine Seite pro Datei' und jede Seite wird als separate PDF heruntergeladen." } },
      { question: { en: "Does splitting reduce PDF quality?", zh: "分割会降低 PDF 质量吗？", ja: "分割すると PDF の品質は下がりますか？", es: "¿Dividir reduce la calidad del PDF?", pt: "Dividir reduz a qualidade do PDF?", fr: "La division réduit-elle la qualité du PDF ?", de: "Verringert das Teilen die PDF-Qualität?" }, answer: { en: "No. The original pages are preserved exactly — no re-rendering or compression.", zh: "不会。原始页面被精确保留，不重新渲染也不压缩。", ja: "いいえ。元のページはそのまま保持され、再レンダリングや圧縮は行われません。", es: "No. Las páginas originales se conservan exactamente, sin re-renderizado ni compresión.", pt: "Não. As páginas originais são preservadas exatamente — sem re-renderização ou compressão.", fr: "Non. Les pages originales sont conservées telles quelles — aucun re-rendu ni compression.", de: "Nein. Die Originalseiten bleiben unverändert — keine Neu-Renderung oder Komprimierung." } },
    ]
  },
  {
    slug: "pdf/compress", category: "pdf", icon: "Minimize2",
    name: { en: "Compress PDF", zh: "压缩 PDF", ja: "PDF 圧縮", es: "Comprimir PDF", pt: "Comprimir PDF", fr: "Compresser PDF", de: "PDF komprimieren" },
    description: { en: "Reduce PDF file size while keeping quality", zh: "在保持质量的同时减小 PDF 文件大小", ja: "品質を保ちながら PDF ファイルサイズを縮小", es: "Reducir el tamaño del PDF manteniendo la calidad", pt: "Reduzir o tamanho do PDF mantendo a qualidade", fr: "Réduire la taille du PDF tout en gardant la qualité", de: "PDF-Dateigröße reduzieren bei erhaltener Qualität" },
    faq: [
      { question: { en: "How much can a PDF be compressed?", zh: "PDF 最多能压缩多少？", ja: "PDF はどれくらい圧縮できますか？", es: "¿Cuánto se puede comprimir un PDF?", pt: "Quanto um PDF pode ser comprimido?", fr: "De combien un PDF peut-il être compressé ?", de: "Wie stark kann eine PDF komprimiert werden?" }, answer: { en: "Image-heavy PDFs can shrink 30% to 70%. Text-only PDFs may shrink only 10% to 20% since text is already compact.", zh: "图片多的 PDF 可缩小 30%-70%。纯文字 PDF 可能只缩小 10%-20%，因为文字本身已很紧凑。", ja: "画像中心の PDF は 30%～70% 縮小できます。テキストのみの PDF は元々小さいため 10%～20% 程度です。", es: "Los PDF con muchas imágenes pueden reducirse un 30% a 70%. Los PDF solo de texto pueden reducirse solo un 10% a 20% ya que el texto ya es compacto.", pt: "PDFs com muitas imagens podem reduzir 30% a 70%. PDFs só de texto podem reduzir apenas 10% a 20%, pois o texto já é compacto.", fr: "Les PDF riches en images peuvent être réduits de 30% à 70%. Les PDF en texte seul peuvent ne réduire que de 10% à 20% car le texte est déjà compact.", de: "Bildlastige PDFs können um 30% bis 70% schrumpfen. Reine Text-PDFs möglicherweise nur 10% bis 20%, da Text bereits kompakt ist." } },
      { question: { en: "Will compression reduce image quality?", zh: "压缩会降低图片质量吗？", ja: "圧縮すると画質は落ちますか？", es: "¿La compresión reduce la calidad de la imagen?", pt: "A compressão reduz a qualidade da imagem?", fr: "La compression réduit-elle la qualité de l'image ?", de: "Verringert die Komprimierung die Bildqualität?" }, answer: { en: "Light and Medium modes keep text perfectly sharp. Strong mode re-renders images at 100 DPI with JPEG quality 0.6 — visible only on close inspection.", zh: "Light 和 Medium 模式文字保持清晰。Strong 模式用 100 DPI 和 JPEG 质量 0.6 重新渲染图片——只有仔细查看才能察觉。", ja: "Light と Medium モードではテキストは鮮明です。Strong モードは 100 DPI・JPEG 品質 0.6 で画像を描画し直すため、近くで見ないと判りません。", es: "Los modos Light y Medium mantienen el texto perfectamente nítido. El modo Strong re-renderiza las imágenes a 100 DPI con calidad JPEG 0.6 — visible solo en inspección cercana.", pt: "Os modos Light e Medium mantêm o texto perfeitamente nítido. O modo Strong re-renderiza as imagens a 100 DPI com qualidade JPEG 0.6 — visível apenas em inspeção próxima.", fr: "Les modes Light et Medium conservent le texte parfaitement net. Le mode Strong re-rendu les images à 100 DPI avec qualité JPEG 0.6 — visible seulement de près.", de: "Light- und Medium-Modi halten Text perfekt scharf. Der Strong-Modus rendert Bilder mit 100 DPI und JPEG-Qualität 0.6 neu — nur bei genauer Betrachtung sichtbar." } },
      { question: { en: "Why is my PDF not getting smaller?", zh: "为什么我的 PDF 没有变小？", ja: "なぜ PDF が小さくならないのですか？", es: "¿Por qué mi PDF no se hace más pequeño?", pt: "Por que meu PDF não está ficando menor?", fr: "Pourquoi mon PDF ne devient-il pas plus petit ?", de: "Warum wird meine PDF nicht kleiner?" }, answer: { en: "If the PDF is mostly text, fonts are already optimized. Already-compressed PDFs (e.g. scanned images) may shrink very little.", zh: "如果 PDF 主要是文字，字体已优化。已经压缩的 PDF（如扫描件）几乎不能再缩小。", ja: "PDF が主にテキストで構成されている場合、フォントは既に最適化されています。既に圧縮された PDF（スキャン画像など）はあまり縮小されません。", es: "Si el PDF es principalmente texto, las fuentes ya están optimizadas. Los PDF ya comprimidos (p. ej. imágenes escaneadas) pueden reducirse muy poco.", pt: "Se o PDF é principalmente texto, as fontes já estão otimizadas. PDFs já comprimidos (ex.: imagens digitalizadas) podem reduzir muito pouco.", fr: "Si le PDF est principalement du texte, les polices sont déjà optimisées. Les PDF déjà compressés (ex. images scannées) peuvent très peu réduire.", de: "Wenn die PDF hauptsächlich Text enthält, sind Schriftarten bereits optimiert. Bereits komprimierte PDFs (z.B. gescannte Bilder) schrumpfen möglicherweise sehr wenig." } },
    ]
  },
  {
    slug: "pdf/to-image", category: "pdf", icon: "Image",
    name: { en: "PDF to Image", zh: "PDF 转图片", ja: "PDF を画像に", es: "PDF a Imagen", pt: "PDF para Imagem", fr: "PDF en Image", de: "PDF zu Bild" },
    description: { en: "Convert each PDF page to PNG or JPG", zh: "将每个 PDF 页面转换为 PNG 或 JPG", ja: "各 PDF ページを PNG または JPG に変換", es: "Convertir cada página PDF a PNG o JPG", pt: "Converter cada página PDF para PNG ou JPG", fr: "Convertir chaque page PDF en PNG ou JPG", de: "Jede PDF-Seite in PNG oder JPG konvertieren" },
    faq: [
      { question: { en: "What DPI should I use?", zh: "我应该用多少 DPI？", ja: "どの DPI を使うべきですか？", es: "¿Qué DPI debo usar?", pt: "Qual DPI devo usar?", fr: "Quel DPI dois-je utiliser ?", de: "Welche DPI soll ich verwenden?" }, answer: { en: "1x (72 DPI) for screen viewing, 2x (144 DPI) for retina displays, 3x-4x for printing. Higher DPI = larger file size.", zh: "屏幕查看用 1x（72 DPI），Retina 屏用 2x（144 DPI），打印用 3x-4x。DPI 越高文件越大。", ja: "画面表示は 1x（72 DPI）、Retina ディスプレイは 2x（144 DPI）、印刷は 3x-4x。DPI が高いほどファイルサイズが大きくなります。", es: "1x (72 DPI) para visualización en pantalla, 2x (144 DPI) para pantallas retina, 3x-4x para impresión. Mayor DPI = mayor tamaño de archivo.", pt: "1x (72 DPI) para visualização em tela, 2x (144 DPI) para telas retina, 3x-4x para impressão. DPI maior = arquivo maior.", fr: "1x (72 DPI) pour l'écran, 2x (144 DPI) pour les écrans retina, 3x-4x pour l'impression. DPI plus élevé = fichier plus volumineux.", de: "1x (72 DPI) für Bildschirmansicht, 2x (144 DPI) für Retina-Displays, 3x-4x für Druck. Höhere DPI = größere Datei." } },
      { question: { en: "PNG vs JPEG — which is better?", zh: "PNG vs JPEG，哪个更好？", ja: "PNG と JPEG、どちらが良いですか？", es: "PNG vs JPEG — ¿cuál es mejor?", pt: "PNG vs JPEG — qual é melhor?", fr: "PNG ou JPEG — lequel est mieux ?", de: "PNG oder JPEG — was ist besser?" }, answer: { en: "PNG is lossless with transparency support but larger files. JPEG is smaller but lossy. Use PNG for screenshots/diagrams, JPEG for photos.", zh: "PNG 无损且支持透明，但文件较大。JPEG 较小但有损。截图/图表用 PNG，照片用 JPEG。", ja: "PNG は可逆圧縮で透明度をサポートしますがファイルが大きくなります。JPEG は小さいですが非可逆。スクリーンショット・図は PNG、写真には JPEG を使用してください。", es: "PNG es sin pérdida y admite transparencia pero archivos más grandes. JPEG es más pequeño pero con pérdida. Usa PNG para capturas/diagramas, JPEG para fotos.", pt: "PNG é sem perdas e suporta transparência, mas com arquivos maiores. JPEG é menor, mas com perdas. Use PNG para capturas/diagramas, JPEG para fotos.", fr: "PNG est sans perte avec prise en charge de la transparence mais fichiers plus volumineux. JPEG est plus petit mais avec perte. Utilisez PNG pour captures/diagrammes, JPEG pour photos.", de: "PNG ist verlustfrei mit Transparenz-Unterstützung, aber größere Dateien. JPEG ist kleiner, aber verlustbehaftet. PNG für Screenshots/Diagramme, JPEG für Fotos." } },
      { question: { en: "Are pages downloaded individually or as a ZIP?", zh: "页面是单独下载还是打包成 ZIP？", ja: "ページは個別にダウンロードされますか、ZIP でですか？", es: "¿Las páginas se descargan individualmente o como ZIP?", pt: "As páginas são baixadas individualmente ou como ZIP?", fr: "Les pages sont-elles téléchargées individuellement ou en ZIP ?", de: "Werden Seiten einzeln oder als ZIP heruntergeladen?" }, answer: { en: "Each page downloads as a separate image. Use a separate tool to ZIP them if needed.", zh: "每页作为单独图片下载。如需打包 ZIP，请使用其他工具。", ja: "各ページは個別の画像としてダウンロードされます。ZIP にする場合は別のツールを使ってください。", es: "Cada página se descarga como una imagen separada. Usa otra herramienta para comprimirlas en ZIP si lo necesitas.", pt: "Cada página é baixada como uma imagem separada. Use outra ferramenta para compactá-las em ZIP, se necessário.", fr: "Chaque page se télécharge comme une image séparée. Utilisez un autre outil pour les zipper si nécessaire.", de: "Jede Seite wird als separates Bild heruntergeladen. Verwenden Sie ggf. ein anderes Tool zum ZIPen." } },
    ]
  },
  { slug: "pdf/image-to-pdf", category: "pdf", icon: "FileImage", name: { en: "Image to PDF", zh: "图片转 PDF", ja: "画像を PDF に", es: "Imagen a PDF", pt: "Imagem para PDF", fr: "Image en PDF", de: "Bild zu PDF" }, description: { en: "Convert images to a single PDF file", zh: "将图片转换为单个 PDF 文件", ja: "画像を 1 つの PDF ファイルに変換", es: "Convertir imágenes a un solo PDF", pt: "Converter imagens em um único PDF", fr: "Convertir des images en un seul PDF", de: "Bilder in eine PDF-Datei konvertieren" } },
  { slug: "pdf/add-watermark", category: "pdf", icon: "Stamp", name: { en: "Add Watermark", zh: "添加水印", ja: "透かし追加", es: "Añadir Marca de Agua", pt: "Adicionar Marca D'água", fr: "Ajouter Filigrane", de: "Wasserzeichen hinzufügen" }, description: { en: "Add text watermark to PDF pages", zh: "向 PDF 页面添加文本水印", ja: "PDF ページにテキスト透かしを追加", es: "Añadir marca de agua de texto a páginas PDF", pt: "Adicionar marca d'água de texto a páginas PDF", fr: "Ajouter un filigrane de texte aux pages PDF", de: "Textwasserzeichen zu PDF-Seiten hinzufügen" } },
  { slug: "pdf/rotate", category: "pdf", icon: "RotateCw", name: { en: "Rotate PDF", zh: "旋转 PDF", ja: "PDF 回転", es: "Rotar PDF", pt: "Girar PDF", fr: "Pivoter PDF", de: "PDF drehen" }, description: { en: "Rotate PDF pages by 90, 180 or 270 degrees", zh: "将 PDF 页面旋转 90、180 或 270 度", ja: "PDF ページを 90、180、270 度回転", es: "Rotar páginas PDF 90, 180 o 270 grados", pt: "Girar páginas PDF em 90, 180 ou 270 graus", fr: "Pivoter les pages PDF de 90, 180 ou 270 degrés", de: "PDF-Seiten um 90, 180 oder 270 Grad drehen" } },
  { slug: "pdf/extract-text", category: "pdf", icon: "FileText", name: { en: "Extract Text", zh: "提取文本", ja: "テキスト抽出", es: "Extraer Texto", pt: "Extrair Texto", fr: "Extraire Texte", de: "Text extrahieren" }, description: { en: "Extract text content from PDF as plain text", zh: "从 PDF 中提取纯文本内容", ja: "PDF からテキストを抽出", es: "Extraer texto del PDF como texto plano", pt: "Extrair texto do PDF como texto simples", fr: "Extraire le texte du PDF en texte brut", de: "Text aus PDF extrahieren" } },
  { slug: "pdf/reorder", category: "pdf", icon: "ListOrdered", name: { en: "Reorder Pages", zh: "重排页面", ja: "ページ並び替え", es: "Reordenar Páginas", pt: "Reordenar Páginas", fr: "Réorganiser Pages", de: "Seiten neu anordnen" }, description: { en: "Drag and drop to reorder PDF pages", zh: "拖放以重新排序 PDF 页面", ja: "ドラッグ&ドロップで PDF ページを並べ替え", es: "Arrastra y suelta para reordenar páginas PDF", pt: "Arraste e solte para reordenar páginas PDF", fr: "Glissez-déposez pour réorganiser les pages PDF", de: "PDF-Seiten per Drag & Drop neu anordnen" } },

  // Image
  { slug: "image/compress", category: "image", icon: "Minimize2", name: { en: "Compress Image", zh: "压缩图片", ja: "画像圧縮", es: "Comprimir Imagen", pt: "Comprimir Imagem", fr: "Compresser Image", de: "Bild komprimieren" }, description: { en: "Reduce image file size with quality control", zh: "在控制质量的同时减小图片大小", ja: "画質を制御しながら画像サイズを縮小", es: "Reducir el tamaño de la imagen con control de calidad", pt: "Reduzir o tamanho da imagem com controle de qualidade", fr: "Réduire la taille de l'image avec contrôle qualité", de: "Bildgröße mit Qualitätskontrolle reduzieren" } },
  { slug: "image/resize", category: "image", icon: "Maximize2", name: { en: "Resize Image", zh: "调整大小", ja: "リサイズ", es: "Redimensionar", pt: "Redimensionar", fr: "Redimensionner", de: "Bild skalieren" }, description: { en: "Resize images to any width and height", zh: "将图片调整为任意宽度和高度", ja: "画像を任意の幅と高さにリサイズ", es: "Redimensionar imágenes a cualquier ancho y alto", pt: "Redimensionar imagens para qualquer largura e altura", fr: "Redimensionner des images à toute largeur et hauteur", de: "Bilder auf beliebige Breite und Höhe skalieren" } },
  { slug: "image/crop", category: "image", icon: "Crop", name: { en: "Crop Image", zh: "裁剪图片", ja: "画像切り取り", es: "Recortar Imagen", pt: "Recortar Imagem", fr: "Recadrer Image", de: "Bild zuschneiden" }, description: { en: "Crop images to remove unwanted areas", zh: "裁剪图片以去除不需要的区域", ja: "不要な領域を削除するために画像を切り取る", es: "Recortar imágenes para eliminar áreas no deseadas", pt: "Recortar imagens para remover áreas indesejadas", fr: "Recadrer des images pour supprimer les zones inutiles", de: "Bilder zuschneiden, um unerwünschte Bereiche zu entfernen" } },
  { slug: "image/convert", category: "image", icon: "RefreshCw", name: { en: "Convert Image", zh: "转换格式", ja: "形式変換", es: "Convertir Formato", pt: "Converter Formato", fr: "Convertir Format", de: "Format konvertieren" }, description: { en: "Convert images between JPG, PNG, WebP, BMP", zh: "在 JPG、PNG、WebP、BMP 之间转换", ja: "JPG、PNG、WebP、BMP 間で画像を変換", es: "Convertir entre JPG, PNG, WebP, BMP", pt: "Converter entre JPG, PNG, WebP, BMP", fr: "Convertir entre JPG, PNG, WebP, BMP", de: "Zwischen JPG, PNG, WebP, BMP konvertieren" } },
  { slug: "image/add-watermark", category: "image", icon: "Stamp", name: { en: "Add Watermark", zh: "添加水印", ja: "透かし追加", es: "Marca de Agua", pt: "Marca D'água", fr: "Filigrane", de: "Wasserzeichen" }, description: { en: "Add text watermark to images", zh: "向图片添加文本水印", ja: "画像にテキスト透かしを追加", es: "Añadir marca de agua de texto a imágenes", pt: "Adicionar marca d'água de texto a imagens", fr: "Ajouter un filigrane de texte aux images", de: "Textwasserzeichen zu Bildern hinzufügen" } },

  // Text
  { slug: "text/char-count", category: "text", icon: "Hash", name: { en: "Character Count", zh: "字符统计", ja: "文字数カウント", es: "Contar Caracteres", pt: "Contar Caracteres", fr: "Compter Caractères", de: "Zeichen zählen" }, description: { en: "Count characters, words, lines and bytes", zh: "统计字符、单词、行数和字节", ja: "文字、単語、行、バイトをカウント", es: "Contar caracteres, palabras, líneas y bytes", pt: "Contar caracteres, palavras, linhas e bytes", fr: "Compter caractères, mots, lignes et octets", de: "Zeichen, Wörter, Zeilen und Bytes zählen" } },
  { slug: "text/case-convert", category: "text", icon: "CaseSensitive", name: { en: "Case Converter", zh: "大小写转换", ja: "大文字小文字変換", es: "Convertir Mayúsculas", pt: "Converter Maiúsculas", fr: "Convertir Casse", de: "Groß-/Kleinschreibung" }, description: { en: "Convert text to upper, lower, title, sentence case", zh: "将文本转换为大写、小写、标题、句首大写", ja: "テキストを大文字、小文字、タイトル文、 文頭大文字に変換", es: "Convertir texto a mayúsculas, minúsculas, título, oración", pt: "Converter texto para maiúsculas, minúsculas, título, frase", fr: "Convertir texte en majuscules, minuscules, titre, phrase", de: "Text in Groß-, Klein-, Titel- oder Satzkleinbuchstaben umwandeln" } },
  { slug: "text/duplicate", category: "text", icon: "CopyX", name: { en: "Remove Duplicates", zh: "去除重复", ja: "重複削除", es: "Eliminar Duplicados", pt: "Remover Duplicados", fr: "Supprimer Doublons", de: "Duplikate entfernen" }, description: { en: "Remove duplicate lines from text", zh: "从文本中删除重复行", ja: "テキストから重複行を削除", es: "Eliminar líneas duplicadas del texto", pt: "Remover linhas duplicadas do texto", fr: "Supprimer les lignes en double du texte", de: "Doppelte Zeilen aus Text entfernen" } },
  { slug: "text/diff", category: "text", icon: "GitCompare", name: { en: "Text Diff", zh: "文本对比", ja: "テキスト比較", es: "Comparar Texto", pt: "Comparar Texto", fr: "Comparer Texte", de: "Text vergleichen" }, description: { en: "Compare two texts and show differences", zh: "比较两个文本并显示差异", ja: "2 つのテキストを比較し、違いを表示", es: "Comparar dos textos y mostrar diferencias", pt: "Comparar dois textos e mostrar diferenças", fr: "Comparer deux textes et afficher les différences", de: "Zwei Texte vergleichen und Unterschiede anzeigen" } },
  { slug: "text/regex", category: "text", icon: "Regex", name: { en: "Regex Tester", zh: "正则测试", ja: "正規表現テスター", es: "Probador Regex", pt: "Testador Regex", fr: "Testeur Regex", de: "Regex-Tester" }, description: { en: "Test and debug regular expressions", zh: "测试和调试正则表达式", ja: "正規表現のテストとデバッグ", es: "Probar y depurar expresiones regulares", pt: "Testar e depurar expressões regulares", fr: "Tester et déboguer des expressions régulières", de: "Reguläre Ausdrücke testen und debuggen" } },

  // Unit
  { slug: "unit/length", category: "unit", icon: "Ruler", name: { en: "Length Converter", zh: "长度换算", ja: "長さ変換", es: "Conversor de Longitud", pt: "Conversor de Comprimento", fr: "Convertisseur de Longueur", de: "Längenumrechner" }, description: { en: "Convert between meters, feet, inches, miles and more", zh: "米、英尺、英寸、英里等单位换算", ja: "メートル、フィート、インチ、マイルなどの変換", es: "Convertir entre metros, pies, pulgadas, millas y más", pt: "Converter entre metros, pés, polegadas, milhas e mais", fr: "Convertir entre mètres, pieds, pouces, miles et plus", de: "Zwischen Meter, Fuß, Zoll, Meilen und mehr umrechnen" } },
  { slug: "unit/weight", category: "unit", icon: "Weight", name: { en: "Weight Converter", zh: "重量换算", ja: "重さ変換", es: "Conversor de Peso", pt: "Conversor de Peso", fr: "Convertisseur de Poids", de: "Gewichtsumrechner" }, description: { en: "Convert between kg, lbs, oz, grams and more", zh: "千克、磅、盎司、克等单位换算", ja: "キログラム、ポンド、オンス、グラムなどの変換", es: "Convertir entre kg, lbs, oz, gramos y más", pt: "Converter entre kg, lbs, oz, gramas e mais", fr: "Convertir entre kg, lbs, oz, grammes et plus", de: "Zwischen kg, lbs, oz, Gramm und mehr umrechnen" } },
  { slug: "unit/temperature", category: "unit", icon: "Thermometer", name: { en: "Temperature Converter", zh: "温度换算", ja: "温度変換", es: "Conversor de Temperatura", pt: "Conversor de Temperatura", fr: "Convertisseur de Température", de: "Temperaturumrechner" }, description: { en: "Convert between Celsius, Fahrenheit, Kelvin", zh: "摄氏、华氏、开尔文之间转换", ja: "摂氏、華氏、ケルビン間で変換", es: "Convertir entre Celsius, Fahrenheit, Kelvin", pt: "Converter entre Celsius, Fahrenheit, Kelvin", fr: "Convertir entre Celsius, Fahrenheit, Kelvin", de: "Zwischen Celsius, Fahrenheit, Kelvin umrechnen" } },
  { slug: "unit/area", category: "unit", icon: "Square", name: { en: "Area Converter", zh: "面积换算", ja: "面積変換", es: "Conversor de Área", pt: "Conversor de Área", fr: "Convertisseur de Surface", de: "Flächenumrechner" }, description: { en: "Convert between m², ft², acres, hectares and more", zh: "平方米、平方英尺、英亩、公顷等单位换算", ja: "平方メートル、平方フィート、エーカー、ヘクタールなど", es: "Convertir entre m², ft², acres, hectáreas y más", pt: "Converter entre m², ft², acres, hectares e mais", fr: "Convertir entre m², ft², acres, hectares et plus", de: "Zwischen m², ft², Acres, Hektar und mehr umrechnen" } },
  { slug: "unit/volume", category: "unit", icon: "Beaker", name: { en: "Volume Converter", zh: "体积换算", ja: "体積変換", es: "Conversor de Volumen", pt: "Conversor de Volume", fr: "Convertisseur de Volume", de: "Volumenumrechner" }, description: { en: "Convert between liters, gallons, cups, ml and more", zh: "升、加仑、杯、毫升等单位换算", ja: "リットル、ガロン、カップ、ミリリットルなど", es: "Convertir entre litros, galones, tazas, ml y más", pt: "Converter entre litros, galões, copos, ml e mais", fr: "Convertir entre litres, gallons, tasses, ml et plus", de: "Zwischen Liter, Gallonen, Tassen, ml und mehr umrechnen" } },
  { slug: "unit/speed", category: "unit", icon: "Gauge", name: { en: "Speed Converter", zh: "速度换算", ja: "速度変換", es: "Conversor de Velocidad", pt: "Conversor de Velocidade", fr: "Convertisseur de Vitesse", de: "Geschwindigkeitsumrechner" }, description: { en: "Convert between km/h, mph, m/s, knots and more", zh: "公里/小时、英里/小时、米/秒、节等单位换算", ja: "km/h、mph、m/s、ノットなどの変換", es: "Convertir entre km/h, mph, m/s, nudos y más", pt: "Converter entre km/h, mph, m/s, nós e mais", fr: "Convertir entre km/h, mph, m/s, nœuds et plus", de: "Zwischen km/h, mph, m/s, Knoten und mehr umrechnen" } },
  { slug: "unit/data", category: "unit", icon: "HardDrive", name: { en: "Data Storage Converter", zh: "数据存储换算", ja: "データ容量変換", es: "Conversor de Almacenamiento", pt: "Conversor de Armazenamento", fr: "Convertisseur de Stockage", de: "Datenspeicher-Umrechner" }, description: { en: "Convert between B, KB, MB, GB, TB, PB", zh: "B、KB、MB、GB、TB、PB 之间转换", ja: "B、KB、MB、GB、TB、PB 間で変換", es: "Convertir entre B, KB, MB, GB, TB, PB", pt: "Converter entre B, KB, MB, GB, TB, PB", fr: "Convertir entre B, KB, MB, GB, TB, PB", de: "Zwischen B, KB, MB, GB, TB, PB umrechnen" } },
  { slug: "unit/time", category: "unit", icon: "Clock", name: { en: "Time Converter", zh: "时间换算", ja: "時間変換", es: "Conversor de Tiempo", pt: "Conversor de Tempo", fr: "Convertisseur de Temps", de: "Zeitumrechner" }, description: { en: "Convert between seconds, minutes, hours, days, years", zh: "秒、分钟、小时、天、年之间转换", ja: "秒、分、時間、日、年の間で変換", es: "Convertir entre segundos, minutos, horas, días, años", pt: "Converter entre segundos, minutos, horas, dias, anos", fr: "Convertir entre secondes, minutes, heures, jours, années", de: "Zwischen Sekunden, Minuten, Stunden, Tagen, Jahren umrechnen" } },

  // Color
  { slug: "color/picker", category: "color", icon: "Pipette", name: { en: "Color Picker", zh: "取色器", ja: "カラーピッカー", es: "Selector de Color", pt: "Seletor de Cor", fr: "Sélecteur de Couleur", de: "Farbwähler" }, description: { en: "Pick colors from images and get HEX, RGB, HSL", zh: "从图片中取色，获取 HEX、RGB、HSL", ja: "画像から色を取得し、HEX、RGB、HSL を取得", es: "Elegir colores de imágenes y obtener HEX, RGB, HSL", pt: "Escolher cores de imagens e obter HEX, RGB, HSL", fr: "Choisir des couleurs dans des images et obtenir HEX, RGB, HSL", de: "Farben aus Bildern wählen und HEX, RGB, HSL erhalten" } },
  { slug: "color/hex-rgb", category: "color", icon: "Palette", name: { en: "HEX/RGB Converter", zh: "HEX/RGB 转换", ja: "HEX/RGB 変換", es: "Conversor HEX/RGB", pt: "Conversor HEX/RGB", fr: "Convertisseur HEX/RGB", de: "HEX/RGB-Konverter" }, description: { en: "Convert between HEX, RGB, HSL and CMYK", zh: "HEX、RGB、HSL、CMYK 之间转换", ja: "HEX、RGB、HSL、CMYK 間で変換", es: "Convertir entre HEX, RGB, HSL y CMYK", pt: "Converter entre HEX, RGB, HSL e CMYK", fr: "Convertir entre HEX, RGB, HSL et CMYK", de: "Zwischen HEX, RGB, HSL und CMYK konvertieren" } },
  { slug: "color/palette", category: "color", icon: "SwatchBook", name: { en: "Palette Generator", zh: "色板生成", ja: "パレット生成", es: "Generador de Paleta", pt: "Gerador de Paleta", fr: "Générateur de Palette", de: "Palettengenerator" }, description: { en: "Generate harmonious color palettes", zh: "生成和谐的颜色搭配", ja: "調和のとれたカラーパレットを生成", es: "Generar paletas de colores armoniosas", pt: "Gerar paletas de cores harmoniosas", fr: "Générer des palettes de couleurs harmonieuses", de: "Harmonische Farbpaletten generieren" } },

  // Crypto
  { slug: "crypto/hash", category: "crypto", icon: "Lock", name: { en: "Hash Generator", zh: "哈希生成", ja: "ハッシュ生成", es: "Generador de Hash", pt: "Gerador de Hash", fr: "Générateur de Hash", de: "Hash-Generator" }, description: { en: "Generate MD5, SHA-1, SHA-256, SHA-512 hashes", zh: "生成 MD5、SHA-1、SHA-256、SHA-512 哈希", ja: "MD5、SHA-1、SHA-256、SHA-512 ハッシュを生成", es: "Generar hashes MD5, SHA-1, SHA-256, SHA-512", pt: "Gerar hashes MD5, SHA-1, SHA-256, SHA-512", fr: "Générer des hashes MD5, SHA-1, SHA-256, SHA-512", de: "MD5, SHA-1, SHA-256, SHA-512 Hashes generieren" } },
  { slug: "crypto/base64", category: "crypto", icon: "Binary", name: { en: "Base64 Encode/Decode", zh: "Base64 编解码", ja: "Base64 エンコード/デコード", es: "Codificar/Decodificar Base64", pt: "Codificar/Decodificar Base64", fr: "Encoder/Décoder Base64", de: "Base64 kodieren/dekodieren" }, description: { en: "Encode and decode Base64 strings", zh: "Base64 字符串的编码和解码", ja: "Base64 文字列のエンコードとデコード", es: "Codificar y decodificar cadenas Base64", pt: "Codificar e decodificar strings Base64", fr: "Encoder et décoder des chaînes Base64", de: "Base64-Strings kodieren und dekodieren" } },
  { slug: "crypto/url-encode", category: "crypto", icon: "Link", name: { en: "URL Encode/Decode", zh: "URL 编解码", ja: "URL エンコード/デコード", es: "Codificar/Decodificar URL", pt: "Codificar/Decodificar URL", fr: "Encoder/Décoder URL", de: "URL kodieren/dekodieren" }, description: { en: "Encode and decode URL-encoded strings", zh: "URL 编码字符串的编码和解码", ja: "URL エンコード文字列のエンコードとデコード", es: "Codificar y decodificar cadenas URL-encoded", pt: "Codificar e decodificar strings URL-encoded", fr: "Encoder et décoder des chaînes URL-encoded", de: "URL-codierte Strings kodieren und dekodieren" } },
  { slug: "crypto/uuid", category: "crypto", icon: "Fingerprint", name: { en: "UUID Generator", zh: "UUID 生成", ja: "UUID 生成", es: "Generador UUID", pt: "Gerador UUID", fr: "Générateur UUID", de: "UUID-Generator" }, description: { en: "Generate UUID v1 and v4 identifiers", zh: "生成 UUID v1 和 v4 标识符", ja: "UUID v1 および v4 識別子を生成", es: "Generar identificadores UUID v1 y v4", pt: "Gerar identificadores UUID v1 e v4", fr: "Générer des identifiants UUID v1 et v4", de: "UUID v1 und v4 Identifikatoren generieren" } },

  // Dev
  { slug: "dev/json-format", category: "dev", icon: "Braces", name: { en: "JSON Formatter", zh: "JSON 格式化", ja: "JSON フォーマッタ", es: "Formateador JSON", pt: "Formatador JSON", fr: "Formateur JSON", de: "JSON-Formatierer" }, description: { en: "Format, validate and beautify JSON", zh: "格式化、验证、美化 JSON", ja: "JSON のフォーマット、検証、整形", es: "Formatear, validar y embellecer JSON", pt: "Formatar, validar e embelezar JSON", fr: "Formater, valider et embellir JSON", de: "JSON formatieren, validieren und verschönern" } },
  { slug: "dev/timestamp", category: "dev", icon: "Timer", name: { en: "Timestamp Converter", zh: "时间戳转换", ja: "タイムスタンプ変換", es: "Conversor Timestamp", pt: "Conversor Timestamp", fr: "Convertisseur Timestamp", de: "Zeitstempel-Konverter" }, description: { en: "Convert between Unix timestamps and dates", zh: "Unix 时间戳和日期之间转换", ja: "Unix タイムスタンプと日付の間で変換", es: "Convertir entre timestamps Unix y fechas", pt: "Converter entre timestamps Unix e datas", fr: "Convertir entre timestamps Unix et dates", de: "Zwischen Unix-Zeitstempeln und Daten umrechnen" } },
  { slug: "dev/qrcode", category: "dev", icon: "QrCode", name: { en: "QR Code Generator", zh: "QR 码生成", ja: "QR コード生成", es: "Generador QR", pt: "Gerador QR", fr: "Générateur QR", de: "QR-Code-Generator" }, description: { en: "Generate QR codes from text or URLs", zh: "从文本或 URL 生成 QR 码", ja: "テキストまたは URL から QR コードを生成", es: "Generar códigos QR desde texto o URLs", pt: "Gerar códigos QR de texto ou URLs", fr: "Générer des codes QR à partir de texte ou d'URLs", de: "QR-Codes aus Text oder URLs generieren" } },
  { slug: "dev/password", category: "dev", icon: "Key", name: { en: "Password Generator", zh: "密码生成", ja: "パスワード生成", es: "Generador de Contraseña", pt: "Gerador de Senha", fr: "Générateur de Mot de Passe", de: "Passwort-Generator" }, description: { en: "Generate strong random passwords", zh: "生成强随机密码", ja: "強力なランダムパスワードを生成", es: "Generar contraseñas aleatorias seguras", pt: "Gerar senhas aleatórias fortes", fr: "Générer des mots de passe aléatoires forts", de: "Starke zufällige Passwörter generieren" } },

  // New tools (will be translated by subagent)
  { slug: "pdf/page-numbers", category: "pdf", icon: "ListOrdered", name: { en: "Add Page Numbers", zh: "添加页码", ja: "ページ番号を追加", es: "Agregar Números de Página", pt: "Adicionar Números de Página", fr: "Ajouter Numéros de Page", de: "Seitenzahlen hinzufügen" }, description: { en: "Stamp page numbers on PDF", zh: "在 PDF 上加盖页码", ja: "PDF にページ番号をスタンプ", es: "Estampar números de página en PDF", pt: "Carimbar números de página no PDF", fr: "Tamponner les numéros de page sur le PDF", de: "Seitenzahlen auf PDF stempeln" } },

  { slug: "pdf/sign", category: "pdf", icon: "PenTool", name: { en: "Sign PDF", zh: "签署 PDF", ja: "PDF に署名", es: "Firmar PDF", pt: "Assinar PDF", fr: "Signer PDF", de: "PDF unterschreiben" }, description: { en: "Draw or type signature on PDF", zh: "在 PDF 上绘制或键入签名", ja: "PDF に署名を描画または入力", es: "Dibujar o escribir firma en PDF", pt: "Desenhar ou digitar assinatura no PDF", fr: "Dessiner ou saisir une signature sur le PDF", de: "Unterschrift auf PDF zeichnen oder eingeben" } },

  { slug: "pdf/metadata", category: "pdf", icon: "FileCog", name: { en: "Edit Metadata", zh: "编辑元数据", ja: "メタデータを編集", es: "Editar Metadatos", pt: "Editar Metadados", fr: "Modifier les Métadonnées", de: "Metadaten bearbeiten" }, description: { en: "Edit PDF title/author/subject", zh: "编辑 PDF 标题/作者/主题", ja: "PDF のタイトル/作成者/件名を編集", es: "Editar título/autor/asunto del PDF", pt: "Editar título/autor/assunto do PDF", fr: "Modifier le titre/auteur/sujet du PDF", de: "PDF-Titel/Autor/Betreff bearbeiten" } },

  { slug: "pdf/header-footer", category: "pdf", icon: "Heading1", name: { en: "Header & Footer", zh: "页眉页脚", ja: "ヘッダーとフッター", es: "Encabezado y Pie", pt: "Cabeçalho e Rodapé", fr: "En-tête et Pied de Page", de: "Kopf- und Fußzeile" }, description: { en: "Add header/footer with text", zh: "用文本添加页眉/页脚", ja: "テキストでヘッダー/フッターを追加", es: "Añadir encabezado/pie con texto", pt: "Adicionar cabeçalho/rodapé com texto", fr: "Ajouter un en-tête/pied de page avec du texte", de: "Kopf-/Fußzeile mit Text hinzufügen" } },

  { slug: "pdf/compare", category: "pdf", icon: "GitCompare", name: { en: "Compare PDFs", zh: "PDF 对比", ja: "PDF を比較", es: "Comparar PDFs", pt: "Comparar PDFs", fr: "Comparer des PDF", de: "PDFs vergleichen" }, description: { en: "Side-by-side PDF comparison", zh: "并排 PDF 比较", ja: "並列の PDF 比較", es: "Comparación de PDF en paralelo", pt: "Comparação de PDF lado a lado", fr: "Comparaison de PDF côte à côte", de: "Side-by-Side PDF-Vergleich" } },

  { slug: "pdf/cropPdf", category: "pdf", icon: "Crop", name: { en: "Crop PDF", zh: "裁剪 PDF", ja: "PDF を切り取り", es: "Recortar PDF", pt: "Recortar PDF", fr: "Recadrer le PDF", de: "PDF zuschneiden" }, description: { en: "Crop PDF page margins", zh: "裁剪 PDF 页边距", ja: "PDF のページ余白を切り取り", es: "Recortar márgenes de página del PDF", pt: "Recortar margens de página do PDF", fr: "Recadrer les marges des pages PDF", de: "PDF-Seitenränder zuschneiden" } },

  { slug: "image/rotate", category: "image", icon: "RotateCw", name: { en: "Rotate Image", zh: "图片旋转", ja: "画像回転", es: "Rotar imagen", pt: "Rotacionar imagem", fr: "Pivoter image", de: "Bild drehen" }, description: { en: "Rotate image by any angle", zh: "按任意角度旋转图片", ja: "任意角度で画像を回転", es: "Rotar imagen en cualquier ángulo", pt: "Rotacionar imagem em qualquer ângulo", fr: "Pivoter l'image selon n'importe quel angle", de: "Bild in jeden Winkel drehen" } },

  { slug: "image/flip", category: "image", icon: "FlipHorizontal2", name: { en: "Flip Image", zh: "翻转图片", ja: "画像反転", es: "Voltear imagen", pt: "Virar imagem", fr: "Retourner image", de: "Bild spiegeln" }, description: { en: "Flip horizontal or vertical", zh: "水平或垂直翻转", ja: "水平または垂直に反転", es: "Volteo horizontal o vertical", pt: "Viragem horizontal ou vertical", fr: "Retournement horizontal ou vertical", de: "Horizontal oder vertikal spiegeln" } },

  { slug: "image/base64", category: "image", icon: "Code", name: { en: "Image to Base64", zh: "图片转 Base64", ja: "画像を Base64 に", es: "Imagen a Base64", pt: "Imagem para Base64", fr: "Image en Base64", de: "Bild zu Base64" }, description: { en: "Convert image to Base64 data URL", zh: "将图片转换为 Base64 数据 URL", ja: "画像を Base64 データ URL に変換", es: "Convertir imagen a URL de datos Base64", pt: "Converter imagem para URL de dados Base64", fr: "Convertir image en URL de données Base64", de: "Bild in Base64-Daten-URL konvertieren" } },

  { slug: "image/exif", category: "image", icon: "Eraser", name: { en: "Remove EXIF", zh: "去除 EXIF", ja: "EXIF 削除", es: "Eliminar EXIF", pt: "Remover EXIF", fr: "Supprimer EXIF", de: "EXIF entfernen" }, description: { en: "Strip EXIF metadata from photos", zh: "从照片中剥离 EXIF 元数据", ja: "写真から EXIF メタデータを削除", es: "Eliminar metadatos EXIF de fotos", pt: "Remover metadados EXIF de fotos", fr: "Supprimer les métadonnées EXIF des photos", de: "EXIF-Metadaten aus Fotos entfernen" } },

  { slug: "image/blur", category: "image", icon: "Droplet", name: { en: "Blur Image", zh: "图片模糊", ja: "画像ぼかし", es: "Desenfocar imagen", pt: "Desfocar imagem", fr: "Flouter image", de: "Bild weichzeichnen" }, description: { en: "Apply Gaussian blur to image", zh: "对图片应用高斯模糊", ja: "画像にガウスぼかしを適用", es: "Aplicar desenfoque gaussiano a la imagen", pt: "Aplicar desfoque gaussiano à imagem", fr: "Appliquer un flou gaussien à l'image", de: "Gaußschen Weichzeichner auf Bild anwenden" } },

  { slug: "image/upscale", category: "image", icon: "ZoomIn", name: { en: "Upscale Image", zh: "图片放大", ja: "画像拡大", es: "Ampliar imagen", pt: "Ampliar imagem", fr: "Agrandir image", de: "Bild hochskalieren" }, description: { en: "Upscale image 2x with smoothing", zh: "2 倍放大图片并平滑", ja: "画像を 2 倍に拡大し平滑化", es: "Ampliar imagen 2x con suavizado", pt: "Ampliar imagem 2x com suavização", fr: "Agrandir l'image 2x avec lissage", de: "Bild 2x hochskalieren mit Glättung" } },

  { slug: "image/meme", category: "image", icon: "Smile", name: { en: "Meme Generator", zh: "表情包生成", ja: "ミームジェネレーター", es: "Generador de memes", pt: "Gerador de memes", fr: "Générateur de mèmes", de: "Meme-Generator" }, description: { en: "Add top/bottom text to image", zh: "在图片上添加顶部/底部文字", ja: "画像に上部/下部のテキストを追加", es: "Agregar texto arriba/abajo a la imagen", pt: "Adicionar texto superior/inferior à imagem", fr: "Ajouter du texte en haut/bas de l'image", de: "Oberen/unteren Text zum Bild hinzufügen" } },

  { slug: "text/reverse", category: "text", icon: "Undo2", name: { en: "Reverse Text", zh: "反转文本", ja: "テキスト反転", es: "Invertir texto", pt: "Inverter texto", fr: "Inverser le texte", de: "Text umkehren" }, description: { en: "Reverse text character order", zh: "反转文本字符顺序", ja: "テキストの文字順を反転", es: "Invertir el orden de los caracteres del texto", pt: "Inverter a ordem dos caracteres do texto", fr: "Inverser l'ordre des caractères du texte", de: "Zeichenreihenfolge des Textes umkehren" } },

  { slug: "text/sort", category: "text", icon: "ArrowUpDown", name: { en: "Sort Lines", zh: "排序行", ja: "行をソート", es: "Ordenar líneas", pt: "Ordenar linhas", fr: "Trier les lignes", de: "Zeilen sortieren" }, description: { en: "Sort lines alphabetically or numerically", zh: "按字母或数字排序行", ja: "行をアルファベット順または数字順にソート", es: "Ordenar líneas alfabética o numéricamente", pt: "Ordenar linhas alfabeticamente ou numericamente", fr: "Trier les lignes par ordre alphabétique ou numérique", de: "Zeilen alphabetisch oder numerisch sortieren" } },

  { slug: "text/lorem", category: "text", icon: "FileText", name: { en: "Lorem Ipsum", zh: "假文", ja: "Lorem Ipsum", es: "Texto Lorem", pt: "Texto Lorem", fr: "Texte Lorem", de: "Lorem-Text" }, description: { en: "Generate placeholder text", zh: "生成占位文本", ja: "プレースホルダテキストを生成", es: "Generar texto de marcador de posición", pt: "Gerar texto de espaço reservado", fr: "Générer du texte de remplissage", de: "Platzhaltertext generieren" } },

  { slug: "text/markdown", category: "text", icon: "FileCode", name: { en: "Markdown Preview", zh: "Markdown 预览", ja: "Markdown プレビュー", es: "Vista previa Markdown", pt: "Visualização Markdown", fr: "Aperçu Markdown", de: "Markdown-Vorschau" }, description: { en: "Live markdown rendering", zh: "实时 Markdown 渲染", ja: "ライブ Markdown レンダリング", es: "Renderizado Markdown en vivo", pt: "Renderização Markdown ao vivo", fr: "Rendu Markdown en direct", de: "Live-Markdown-Rendering" } },

  { slug: "text/fancy", category: "text", icon: "Sparkles", name: { en: "Fancy Text", zh: "花式文字", ja: "ファンシーテキスト", es: "Texto elegante", pt: "Texto elegante", fr: "Texte fantaisie", de: "Schicker Text" }, description: { en: "Unicode stylized text", zh: "Unicode 风格化文字", ja: "Unicode スタイリングテキスト", es: "Texto estilizado Unicode", pt: "Texto estilizado Unicode", fr: "Texte stylisé Unicode", de: "Unicode-stilisierter Text" } },

  { slug: "text/rot13", category: "text", icon: "Lock", name: { en: "ROT13", zh: "ROT13", ja: "ROT13 暗号化/復号化", es: "ROT13 cifrado codificar/decodificar", pt: "ROT13 cifra codificar/decodificar", fr: "ROT13 chiffrement encoder/décoder", de: "ROT13 Verschlüsselung kodieren/dekodieren" }, description: { en: "ROT13 cipher encode/decode", zh: "ROT13 密码编/解码", ja: "ROT13 暗号のエンコード/デコード", es: "Codificar/decodificar cifrado ROT13", pt: "Codificar/decodificar cifra ROT13", fr: "Encoder/décoder chiffre ROT13", de: "ROT13-Chiffre kodieren/dekodieren" } },

  { slug: "unit/pressure", category: "unit", icon: "Gauge", name: { en: "Pressure Converter", zh: "压力换算", ja: "圧力変換", es: "Conversor de Presión", pt: "Conversor de Pressão", fr: "Convertisseur de Pression", de: "Druckumrechner" }, description: { en: "Convert between Pa, bar, psi, atm", zh: "转换 Pa、bar、psi、atm 等压力单位", ja: "Pa、bar、psi、atm 間の圧力変換", es: "Convertir entre Pa, bar, psi, atm y más", pt: "Converter entre Pa, bar, psi, atm e mais", fr: "Convertir entre Pa, bar, psi, atm et plus", de: "Zwischen Pa, bar, psi, atm und mehr umrechnen" } },

  { slug: "unit/energy", category: "unit", icon: "Zap", name: { en: "Energy Converter", zh: "能量换算", ja: "エネルギー変換", es: "Conversor de Energía", pt: "Conversor de Energia", fr: "Convertisseur d'Énergie", de: "Energieumrechner" }, description: { en: "Convert J, kJ, cal, kcal, Wh, kWh", zh: "转换 J、kJ、cal、kcal、Wh、kWh 等能量单位", ja: "J、kJ、cal、kcal、Wh、kWh 間の変換", es: "Convertir entre J, kJ, cal, kcal, Wh, kWh", pt: "Converter entre J, kJ, cal, kcal, Wh, kWh", fr: "Convertir entre J, kJ, cal, kcal, Wh, kWh", de: "Zwischen J, kJ, cal, kcal, Wh, kWh umrechnen" } },

  { slug: "unit/power", category: "unit", icon: "Power", name: { en: "Power Converter", zh: "功率换算", ja: "電力変換", es: "Conversor de Potencia", pt: "Conversor de Potência", fr: "Convertisseur de Puissance", de: "Leistungsumrechner" }, description: { en: "Watt, kW, MW, HP conversions", zh: "瓦特、千瓦、兆瓦、马力换算", ja: "ワット、キロワット、メガワット、馬力の変換", es: "Conversiones de vatio, kW, MW, HP", pt: "Conversões de watt, kW, MW, HP", fr: "Conversions watt, kW, MW, HP", de: "Umrechnungen zwischen Watt, kW, MW, PS" } },

  { slug: "unit/fuel", category: "unit", icon: "Fuel", name: { en: "Fuel Economy", zh: "油耗换算", ja: "燃費変換", es: "Economía de Combustible", pt: "Economia de Combustível", fr: "Économie de Carburant", de: "Kraftstoffverbrauch" }, description: { en: "MPG, L/100km, km/L fuel conversions", zh: "MPG、L/100km、km/L 油耗换算", ja: "MPG、L/100km、km/L 間の燃費変換", es: "Conversiones de MPG, L/100km, km/L", pt: "Conversões de MPG, L/100km, km/L", fr: "Conversions MPG, L/100km, km/L", de: "Umrechnungen MPG, L/100km, km/L" } },

  { slug: "color/gradient", category: "color", icon: "PaintBucket", name: { en: "CSS Gradient", zh: "CSS 渐变", ja: "CSS グラデーション", es: "Gradiente CSS", pt: "Gradiente CSS", fr: "Dégradé CSS", de: "CSS-Verlauf" }, description: { en: "Visual CSS gradient generator", zh: "可视化 CSS 渐变生成器", ja: "ビジュアル CSS グラデーションジェネレーター", es: "Generador visual de gradientes CSS", pt: "Gerador visual de gradientes CSS", fr: "Générateur visuel de dégradés CSS", de: "Visueller CSS-Verlauf-Generator" } },

  { slug: "color/contrast", category: "color", icon: "Contrast", name: { en: "Contrast Checker", zh: "对比度检测", ja: "コントラストチェッカー", es: "Verificador de Contraste", pt: "Verificador de Contraste", fr: "Vérificateur de Contraste", de: "Kontrastprüfer" }, description: { en: "WCAG color contrast ratio", zh: "WCAG 颜色对比度比率", ja: "WCAG 色コントラスト比", es: "Relación de contraste de color WCAG", pt: "Proporção de contraste de cor WCAG", fr: "Rapport de contraste des couleurs WCAG", de: "WCAG-Farbkontrastverhältnis" } },

  { slug: "color/mixer", category: "color", icon: "Blend", name: { en: "Color Mixer", zh: "颜色混合", ja: "カラーミキサー", es: "Mezclador de Colores", pt: "Misturador de Cores", fr: "Mélangeur de Couleurs", de: "Farbmischer" }, description: { en: "Mix two colors to get result", zh: "混合两种颜色得到结果", ja: "2 色を混合して結果を取得", es: "Mezclar dos colores para obtener resultado", pt: "Misturar duas cores para obter resultado", fr: "Mélanger deux couleurs pour obtenir un résultat", de: "Zwei Farben mischen, um Ergebnis zu erhalten" } },

  { slug: "color/named", category: "color", icon: "Tag", name: { en: "Named Colors", zh: "命名颜色", ja: "名前付きカラー", es: "Colores Nombrados", pt: "Cores Nomeadas", fr: "Couleurs Nommées", de: "Benannte Farben" }, description: { en: "Browse 140+ CSS named colors", zh: "浏览 140+ CSS 命名颜色", ja: "140 以上の CSS 名前付きカラーを参照", es: "Explorar más de 140 colores con nombre CSS", pt: "Explorar mais de 140 cores nomeadas CSS", fr: "Parcourir plus de 140 couleurs CSS nommées", de: "Über 140 benannte CSS-Farben durchsuchen" } },

  { slug: "crypto/jwt", category: "crypto", icon: "KeyRound", name: { en: "JWT Decoder", zh: "JWT 解码", ja: "JWT デコーダー", es: "Decodificador JWT", pt: "Decodificador JWT", fr: "Décodeur JWT", de: "JWT-Decoder" }, description: { en: "Decode JSON Web Tokens", zh: "解码 JSON Web 令牌", ja: "JSON Web トークンをデコード", es: "Decodificar JSON Web Tokens", pt: "Decodificar JSON Web Tokens", fr: "Décoder les JSON Web Tokens", de: "JSON Web Tokens dekodieren" } },

  { slug: "crypto/hmac", category: "crypto", icon: "Fingerprint", name: { en: "HMAC Generator", zh: "HMAC 生成器", ja: "HMAC ジェネレーター", es: "Generador HMAC", pt: "Gerador HMAC", fr: "Générateur HMAC", de: "HMAC-Generator" }, description: { en: "Generate HMAC-SHA256 signatures", zh: "生成 HMAC-SHA256 签名", ja: "HMAC-SHA256 署名を生成", es: "Generar firmas HMAC-SHA256", pt: "Gerar assinaturas HMAC-SHA256", fr: "Générer des signatures HMAC-SHA256", de: "HMAC-SHA256-Signaturen generieren" } },

  { slug: "crypto/checksum", category: "crypto", icon: "FileLock2", name: { en: "File Checksum", zh: "文件校验和", ja: "ファイルチェックサム", es: "Suma de Verificación de Archivo", pt: "Soma de Verificação de Arquivo", fr: "Somme de Contrôle de Fichier", de: "Datei-Prüfsumme" }, description: { en: "Compute MD5/SHA-256 file hash", zh: "计算 MD5/SHA-256 文件哈希", ja: "MD5/SHA-256 ファイルハッシュを計算", es: "Calcular hash MD5/SHA-256 de archivo", pt: "Calcular hash MD5/SHA-256 de arquivo", fr: "Calculer le hash MD5/SHA-256 d'un fichier", de: "MD5/SHA-256-Dateihash berechnen" } },

  { slug: "dev/yamlJson", category: "dev", icon: "FileJson", name: { en: "YAML ⇄ JSON", zh: "YAML ⇄ JSON", ja: "YAML ⇄ JSON", es: "YAML ⇄ JSON", pt: "YAML ⇄ JSON", fr: "YAML ⇄ JSON", de: "YAML ⇄ JSON" }, description: { en: "Convert between YAML and JSON", zh: "在 YAML 和 JSON 之间转换", ja: "YAML と JSON 間で変換", es: "Convertir entre YAML y JSON", pt: "Converter entre YAML e JSON", fr: "Convertir entre YAML et JSON", de: "Zwischen YAML und JSON konvertieren" } },

  { slug: "dev/csv", category: "dev", icon: "Table", name: { en: "CSV ⇄ JSON", zh: "CSV ⇄ JSON", ja: "CSV ⇄ JSON", es: "CSV ⇄ JSON", pt: "CSV ⇄ JSON", fr: "CSV ⇄ JSON", de: "CSV ⇄ JSON" }, description: { en: "Convert CSV to/from JSON", zh: "在 CSV 和 JSON 之间转换", ja: "CSV と JSON 間で変換", es: "Convertir CSV a/desde JSON", pt: "Converter CSV de/para JSON", fr: "Convertir CSV vers/depuis JSON", de: "CSV zu/von JSON konvertieren" } },

  { slug: "dev/sql", category: "dev", icon: "Database", name: { en: "SQL Formatter", zh: "SQL 格式化", ja: "SQL フォーマッタ", es: "Formateador SQL", pt: "Formatador SQL", fr: "Formateur SQL", de: "SQL-Formatierer" }, description: { en: "Format and beautify SQL queries", zh: "格式化和美化 SQL 查询", ja: "SQL クエリをフォーマットおよび美化", es: "Formatear y embellecer consultas SQL", pt: "Formatar e embelezar consultas SQL", fr: "Formater et embellir les requêtes SQL", de: "SQL-Abfragen formatieren und verschönern" } },

  { slug: "dev/xml", category: "dev", icon: "FileCode2", name: { en: "XML Formatter", zh: "XML 格式化", ja: "XML フォーマッタ", es: "Formateador XML", pt: "Formatador XML", fr: "Formateur XML", de: "XML-Formatierer" }, description: { en: "Format and validate XML", zh: "格式化和验证 XML", ja: "XML をフォーマットおよび検証", es: "Formatear y validar XML", pt: "Formatar e validar XML", fr: "Formater et valider XML", de: "XML formatieren und validieren" } },
];

export const getToolsByCategory = (category: Tool["category"]) =>
  tools.filter((t) => t.category === category);

export const getToolBySlug = (slug: string) =>
  tools.find((t) => t.slug === slug);
