import type { Locale } from "./config";

export type ToolSlug =
  | "pdf/merge"
  | "pdf/split"
  | "pdf/compress"
  | "pdf/to-image"
  | "pdf/image-to-pdf"
  | "pdf/add-watermark"
  | "pdf/rotate"
  | "pdf/extract-text"
  | "pdf/reorder"
  | "image/compress"
  | "image/resize"
  | "image/crop"
  | "image/convert"
  | "image/add-watermark"
  | "text/char-count"
  | "text/case-convert"
  | "text/duplicate"
  | "text/diff"
  | "text/regex"
  | "unit/length"
  | "unit/weight"
  | "unit/temperature"
  | "unit/area"
  | "unit/volume"
  | "unit/speed"
  | "unit/data"
  | "unit/time"
  | "color/picker"
  | "color/hex-rgb"
  | "color/palette"
  | "crypto/hash"
  | "crypto/base64"
  | "crypto/url-encode"
  | "crypto/uuid"
  | "dev/json-format"
  | "dev/timestamp"
  | "dev/qrcode"
  | "dev/password"
  | "pdf/protect"
  | "pdf/unlock"
  | "pdf/page-numbers"
  | "pdf/sign"
  | "pdf/metadata"
  | "pdf/header-footer"
  | "pdf/compare"
  | "pdf/cropPdf"
  | "image/rotate"
  | "image/flip"
  | "image/base64"
  | "image/exif"
  | "image/blur"
  | "image/upscale"
  | "image/meme"
  | "text/reverse"
  | "text/sort"
  | "text/lorem"
  | "text/markdown"
  | "text/fancy"
  | "text/rot13"
  | "unit/pressure"
  | "unit/energy"
  | "unit/power"
  | "unit/fuel"
  | "color/gradient"
  | "color/contrast"
  | "color/mixer"
  | "color/named"
  | "crypto/jwt"
  | "crypto/hmac"
  | "crypto/checksum"
  | "dev/yamlJson"
  | "dev/csv"
  | "dev/sql"
  | "dev/xml";

export type Tool = {
  slug: ToolSlug;
  category: "pdf" | "image" | "text" | "unit" | "color" | "crypto" | "dev";
  icon: string;
  name: Record<Locale, string>;
  description: Record<Locale, string>;
  /** FAQ: each entry is { question, answer } localized for all 7 languages */
  faq?: Array<{ question: Record<Locale, string>; answer: Record<Locale, string> }>;
};

// 工具图标用 lucide-react 名字
export const tools: Tool[] = [
  // PDF
  {
    slug: "pdf/merge", category: "pdf", icon: "Combine",
    name: { en: "Merge PDF", zh: "合并 PDF", ja: "PDF 結合", es: "Combinar PDF", pt: "Mesclar PDF", fr: "Fusionner PDF", de: "PDF zusammenführen" },
    description: { en: "Combine multiple PDF files into one", zh: "将多个 PDF 合并为一个", ja: "複数の PDF を 1 つに結合", es: "Combinar varios PDF en uno", pt: "Combine vários PDFs em um", fr: "Combinez plusieurs PDF en un", de: "Mehrere PDFs in einer Datei kombinieren" },
    faq: [
      { question: { en: "Is the PDF merge tool free?", zh: "PDF 合并工具免费吗？", ja: "PDF 結合ツールは無料ですか？", es: "¿La herramienta de fusión de PDF es gratuita?", pt: "A ferramenta de mesclagem de PDF é gratuita?", fr: "L'outil de fusion PDF est-il gratuit ?", de: "Ist das PDF-Zusammenführungs-Tool kostenlos?" }, answer: { en: "Yes, completely free. No signup, no watermark, no file limits.", zh: "完全免费。无需注册，无水印，无文件限制。", ja: "はい、完全無料。登録不要、透かしなし、ファイル制限なし。", es: "Sí, totalmente gratis. Sin registro, sin marca de agua, sin límite de archivos.", pt: "Sim, totalmente gratuito. Sem cadastro, sem marca d'água, sem limites de arquivo.", fr: "Oui, totalement gratuit. Pas d'inscription, pas de filigrane, pas de limite de fichiers.", de: "Ja, völlig kostenlos. Keine Registrierung, kein Wasserzeichen, keine Dateibeschränkungen." } },
      { question: { en: "Are my PDF files uploaded to a server?", zh: "我的 PDF 文件会上传到服务器吗？", ja: "PDF ファイルはサーバーにアップロードされますか？", es: "¿Mis archivos PDF se suben a un servidor?", pt: "Meus arquivos PDF são enviados para um servidor?", fr: "Mes fichiers PDF sont-ils téléchargés sur un serveur ?", de: "Werden meine PDF-Dateien auf einen Server hochgeladen?" }, answer: { en: "No. All merging happens in your browser using pdf-lib. Your files never leave your device.", zh: "不会。所有合并操作在您的浏览器中通过 pdf-lib 完成，文件不会离开您的设备。", ja: "いいえ、すべての結合は pdf-lib を使ってブラウザ内で行われ、ファイルがデバイスを離れることはありません。", es: "No. Toda la fusión ocurre en tu navegador usando pdf-lib. Tus archivos nunca salen de tu dispositivo.", pt: "Não. Toda a mesclagem acontece no seu navegador usando pdf-lib. Seus arquivos nunca saem do seu dispositivo.", fr: "Non. Toute la fusion se fait dans votre navigateur via pdf-lib. Vos fichiers ne quittent jamais votre appareil.", de: "Nein. Das Zusammenführen erfolgt im Browser mit pdf-lib. Ihre Dateien verlassen Ihr Gerät nie." } },
      { question: { en: "Is there a limit on how many PDFs I can merge?", zh: "可以合并的 PDF 数量有上限吗？", ja: "結合できる PDF の数に上限はありますか？", es: "¿Hay un límite en la cantidad de PDFs que puedo combinar?", pt: "Há um limite de quantos PDFs posso mesclar?", fr: "Y a-t-il une limite au nombre de PDF que je peux fusionner ?", de: "Gibt es eine Begrenzung für die Anzahl der PDFs, die ich zusammenführen kann?" }, answer: { en: "No hard limit, but very large files may be slow due to browser memory.", zh: "没有硬性限制，但非常大的文件可能因浏览器内存变慢。", ja: "厳密な上限はありませんが、非常に大きなファイルはブラウザメモリの関係で遅くなる場合があります。", es: "Sin límite estricto, pero archivos muy grandes pueden ser lentos por la memoria del navegador.", pt: "Sem limite rígido, mas arquivos muito grandes podem ficar lentos devido à memória do navegador.", fr: "Pas de limite stricte, mais les très gros fichiers peuvent être lents à cause de la mémoire du navigateur.", de: "Keine harte Grenze, aber sehr große Dateien können wegen des Browser-Speichers langsam sein." } },
    ]
  },
  {
    slug: "pdf/split", category: "pdf", icon: "Scissors",
    name: { en: "Split PDF", zh: "分割 PDF", ja: "PDF 分割", es: "Dividir PDF", pt: "Dividir PDF", fr: "Diviser PDF", de: "PDF teilen" },
    description: { en: "Split PDF into separate pages or ranges", zh: "将 PDF 拆分为单独页面或范围", ja: "PDF を個別のページまたは範囲に分割", es: "Dividir PDF en páginas o rangos separados", pt: "Dividir PDF em páginas ou intervalos separados", fr: "Diviser un PDF en pages séparées", de: "PDF in separate Seiten oder Bereiche aufteilen" },
    faq: [
      { question: { en: "How do I split specific pages?", zh: "如何分割指定页面？", ja: "特定のページを分割するには？", es: "¿Cómo divido páginas específicas?", pt: "Como divido páginas específicas?", fr: "Comment diviser des pages spécifiques ?", de: "Wie teile ich bestimmte Seiten?" }, answer: { en: "Use the 'Custom range' mode and enter ranges like '1-3, 5, 7-9' to extract exactly those pages into a new PDF.", zh: "使用'自定义范围'模式，输入类似 '1-3, 5, 7-9' 这样的范围即可将这些页提取为新 PDF。", ja: "「カスタム範囲」モードを使い、「1-3, 5, 7-9」のような範囲を入力すると、そのページだけを新しい PDF に抽出できます。", es: "Usa el modo 'Rango personalizado' e ingresa rangos como '1-3, 5, 7-9' para extraer exactamente esas páginas en un nuevo PDF.", pt: "Use o modo 'Intervalo personalizado' e insira intervalos como '1-3, 5, 7-9' para extrair exatamente essas páginas em um novo PDF.", fr: "Utilisez le mode 'Plage personnalisée' et entrez des plages comme '1-3, 5, 7-9' pour extraire exactement ces pages dans un nouveau PDF.", de: "Verwenden Sie den Modus 'Benutzerdefinierter Bereich' und geben Sie Bereiche wie '1-3, 5, 7-9' ein, um genau diese Seiten in eine neue PDF zu extrahieren." } },
      { question: { en: "Can I split a PDF into individual pages?", zh: "可以把 PDF 拆分成单独的页面吗？", ja: "PDF を 1 ページずつに分割できますか？", es: "¿Puedo dividir un PDF en páginas individuales?", pt: "Posso dividir um PDF em páginas individuais?", fr: "Puis-je diviser un PDF en pages individuelles ?", de: "Kann ich ein PDF in einzelne Seiten aufteilen?" }, answer: { en: "Yes. Use the 'One page per file' mode and each page becomes a separate PDF download.", zh: "可以。使用'每页一文件'模式，每页会成为单独的 PDF 下载。", ja: "はい。「1 ページずつファイル」モードを使うと、各ページが個別の PDF としてダウンロードされます。", es: "Sí. Usa el modo 'Una página por archivo' y cada página se descargará como un PDF separado.", pt: "Sim. Use o modo 'Uma página por arquivo' e cada página se tornará um download de PDF separado.", fr: "Oui. Utilisez le mode 'Une page par fichier' et chaque page devient un téléchargement PDF séparé.", de: "Ja. Verwenden Sie den Modus 'Eine Seite pro Datei' und jede Seite wird als separate PDF heruntergeladen." } },
      { question: { en: "Does splitting reduce PDF quality?", zh: "分割会降低 PDF 质量吗？", ja: "分割すると PDF の品質は下がりますか？", es: "¿Dividir reduce la calidad del PDF?", pt: "Dividir reduz a qualidade do PDF?", fr: "La division réduit-elle la qualité du PDF ?", de: "Verringert das Teilen die PDF-Qualität?" }, answer: { en: "No. The original pages are preserved exactly — no re-rendering or compression.", zh: "不会。原始页面被精确保留，不重新渲染也不压缩。", ja: "いいえ。元のページはそのまま保持され、再レンダリングや圧縮は行われません。", es: "No. Las páginas originales se conservan exactamente, sin re-renderizado ni compresión.", pt: "Não. As páginas originais são preservadas exatamente — sem re-renderização ou compressão.", fr: "Non. Les pages originales sont conservées telles quelles — aucun re-rendu ni compression.", de: "Nein. Die Originalseiten bleiben unverändert — keine Neu-Renderung oder Komprimierung." } },
    ]
  },
  {
    slug: "pdf/compress", category: "pdf", icon: "Minimize2",
    name: { en: "Compress PDF", zh: "压缩 PDF", ja: "PDF 圧縮", es: "Comprimir PDF", pt: "Comprimir PDF", fr: "Compresser PDF", de: "PDF komprimieren" },
    description: { en: "Reduce PDF file size while keeping quality", zh: "在保持质量的同时减小 PDF 文件大小", ja: "品質を保ちながら PDF ファイルサイズを縮小", es: "Reducir el tamaño del PDF manteniendo la calidad", pt: "Reduzir o tamanho do PDF mantendo a qualidade", fr: "Réduire la taille du PDF tout en gardant la qualité", de: "PDF-Dateigröße reduzieren bei erhaltener Qualität" },
    faq: [
      { question: { en: "How much can a PDF be compressed?", zh: "PDF 最多能压缩多少？", ja: "PDF はどれくらい圧縮できますか？", es: "¿Cuánto se puede comprimir un PDF?", pt: "Quanto um PDF pode ser comprimido?", fr: "De combien un PDF peut-il être compressé ?", de: "Wie stark kann eine PDF komprimiert werden?" }, answer: { en: "Image-heavy PDFs can shrink 30% to 70%. Text-only PDFs may shrink only 10% to 20% since text is already compact.", zh: "图片多的 PDF 可缩小 30%-70%。纯文字 PDF 可能只缩小 10%-20%，因为文字本身已很紧凑。", ja: "画像中心の PDF は 30%～70% 縮小できます。テキストのみの PDF は元々小さいため 10%～20% 程度です。", es: "Los PDF con muchas imágenes pueden reducirse un 30% a 70%. Los PDF solo de texto pueden reducirse solo un 10% a 20% ya que el texto ya es compacto.", pt: "PDFs com muitas imagens podem reduzir 30% a 70%. PDFs só de texto podem reduzir apenas 10% a 20%, pois o texto já é compacto.", fr: "Les PDF riches en images peuvent être réduits de 30% à 70%. Les PDF en texte seul peuvent ne réduire que de 10% à 20% car le texte est déjà compact.", de: "Bildlastige PDFs können um 30% bis 70% schrumpfen. Reine Text-PDFs möglicherweise nur 10% bis 20%, da Text bereits kompakt ist." } },
      { question: { en: "Will compression reduce image quality?", zh: "压缩会降低图片质量吗？", ja: "圧縮すると画質は落ちますか？", es: "¿La compresión reduce la calidad de la imagen?", pt: "A compressão reduz a qualidade da imagem?", fr: "La compression réduit-elle la qualité de l'image ?", de: "Verringert die Komprimierung die Bildqualität?" }, answer: { en: "Light and Medium modes keep text perfectly sharp. Strong mode re-renders images at 100 DPI with JPEG quality 0.6 — visible only on close inspection.", zh: "Light 和 Medium 模式文字保持清晰。Strong 模式用 100 DPI 和 JPEG 质量 0.6 重新渲染图片——只有仔细查看才能察觉。", ja: "Light と Medium モードではテキストは鮮明です。Strong モードは 100 DPI・JPEG 品質 0.6 で画像を描画し直すため、近くで見ないと判りません。", es: "Los modos Light y Medium mantienen el texto perfectamente nítido. El modo Strong re-renderiza las imágenes a 100 DPI con calidad JPEG 0.6 — visible solo en inspección cercana.", pt: "Os modos Light e Medium mantêm o texto perfeitamente nítido. O modo Strong re-renderiza as imagens a 100 DPI com qualidade JPEG 0.6 — visível apenas em inspeção próxima.", fr: "Les modes Light et Medium conservent le texte parfaitement net. Le mode Strong re-rendu les images à 100 DPI avec qualité JPEG 0.6 — visible seulement de près.", de: "Light- und Medium-Modi halten Text perfekt scharf. Der Strong-Modus rendert Bilder mit 100 DPI und JPEG-Qualität 0.6 neu — nur bei genauer Betrachtung sichtbar." } },
      { question: { en: "Why is my PDF not getting smaller?", zh: "为什么我的 PDF 没有变小？", ja: "なぜ PDF が小さくならないのですか？", es: "¿Por qué mi PDF no se hace más pequeño?", pt: "Por que meu PDF não está ficando menor?", fr: "Pourquoi mon PDF ne devient-il pas plus petit ?", de: "Warum wird meine PDF nicht kleiner?" }, answer: { en: "If the PDF is mostly text, fonts are already optimized. Already-compressed PDFs (e.g. scanned images) may shrink very little.", zh: "如果 PDF 主要是文字，字体已优化。已经压缩的 PDF（如扫描件）几乎不能再缩小。", ja: "PDF が主にテキストで構成されている場合、フォントは既に最適化されています。既に圧縮された PDF（スキャン画像など）はあまり縮小されません。", es: "Si el PDF es principalmente texto, las fuentes ya están optimizadas. Los PDF ya comprimidos (p. ej. imágenes escaneadas) pueden reducirse muy poco.", pt: "Se o PDF é principalmente texto, as fontes já estão otimizadas. PDFs já comprimidos (ex.: imagens digitalizadas) podem reduzir muito pouco.", fr: "Si le PDF est principalement du texte, les polices sont déjà optimisées. Les PDF déjà compressés (ex. images scannées) peuvent très peu réduire.", de: "Wenn die PDF hauptsächlich Text enthält, sind Schriftarten bereits optimiert. Bereits komprimierte PDFs (z.B. gescannte Bilder) schrumpfen möglicherweise sehr wenig." } },
    ]
  },
  {
    slug: "pdf/to-image", category: "pdf", icon: "Image",
    name: { en: "PDF to Image", zh: "PDF 转图片", ja: "PDF を画像に", es: "PDF a Imagen", pt: "PDF para Imagem", fr: "PDF en Image", de: "PDF zu Bild" },
    description: { en: "Convert each PDF page to PNG or JPG", zh: "将每个 PDF 页面转换为 PNG 或 JPG", ja: "各 PDF ページを PNG または JPG に変換", es: "Convertir cada página PDF a PNG o JPG", pt: "Converter cada página PDF para PNG ou JPG", fr: "Convertir chaque page PDF en PNG ou JPG", de: "Jede PDF-Seite in PNG oder JPG konvertieren" },
    faq: [
      { question: { en: "What DPI should I use?", zh: "我应该用多少 DPI？", ja: "どの DPI を使うべきですか？", es: "¿Qué DPI debo usar?", pt: "Qual DPI devo usar?", fr: "Quel DPI dois-je utiliser ?", de: "Welche DPI soll ich verwenden?" }, answer: { en: "1x (72 DPI) for screen viewing, 2x (144 DPI) for retina displays, 3x-4x for printing. Higher DPI = larger file size.", zh: "屏幕查看用 1x（72 DPI），Retina 屏用 2x（144 DPI），打印用 3x-4x。DPI 越高文件越大。", ja: "画面表示は 1x（72 DPI）、Retina ディスプレイは 2x（144 DPI）、印刷は 3x-4x。DPI が高いほどファイルサイズが大きくなります。", es: "1x (72 DPI) para visualización en pantalla, 2x (144 DPI) para pantallas retina, 3x-4x para impresión. Mayor DPI = mayor tamaño de archivo.", pt: "1x (72 DPI) para visualização em tela, 2x (144 DPI) para telas retina, 3x-4x para impressão. DPI maior = arquivo maior.", fr: "1x (72 DPI) pour l'écran, 2x (144 DPI) pour les écrans retina, 3x-4x pour l'impression. DPI plus élevé = fichier plus volumineux.", de: "1x (72 DPI) für Bildschirmansicht, 2x (144 DPI) für Retina-Displays, 3x-4x für Druck. Höhere DPI = größere Datei." } },
      { question: { en: "PNG vs JPEG — which is better?", zh: "PNG vs JPEG，哪个更好？", ja: "PNG と JPEG、どちらが良いですか？", es: "PNG vs JPEG — ¿cuál es mejor?", pt: "PNG vs JPEG — qual é melhor?", fr: "PNG ou JPEG — lequel est mieux ?", de: "PNG oder JPEG — was ist besser?" }, answer: { en: "PNG is lossless with transparency support but larger files. JPEG is smaller but lossy. Use PNG for screenshots/diagrams, JPEG for photos.", zh: "PNG 无损且支持透明，但文件较大。JPEG 较小但有损。截图/图表用 PNG，照片用 JPEG。", ja: "PNG は可逆圧縮で透明度をサポートしますがファイルが大きくなります。JPEG は小さいですが非可逆。スクリーンショット・図は PNG、写真には JPEG を使用してください。", es: "PNG es sin pérdida y admite transparencia pero archivos más grandes. JPEG es más pequeño pero con pérdida. Usa PNG para capturas/diagramas, JPEG para fotos.", pt: "PNG é sem perdas e suporta transparência, mas com arquivos maiores. JPEG é menor, mas com perdas. Use PNG para capturas/diagramas, JPEG para fotos.", fr: "PNG est sans perte avec prise en charge de la transparence mais fichiers plus volumineux. JPEG est plus petit mais avec perte. Utilisez PNG pour captures/diagrammes, JPEG pour photos.", de: "PNG ist verlustfrei mit Transparenz-Unterstützung, aber größere Dateien. JPEG ist kleiner, aber verlustbehaftet. PNG für Screenshots/Diagramme, JPEG für Fotos." } },
      { question: { en: "Are pages downloaded individually or as a ZIP?", zh: "页面是单独下载还是打包成 ZIP？", ja: "ページは個別にダウンロードされますか、ZIP でですか？", es: "¿Las páginas se descargan individualmente o como ZIP?", pt: "As páginas são baixadas individualmente ou como ZIP?", fr: "Les pages sont-elles téléchargées individuellement ou en ZIP ?", de: "Werden Seiten einzeln oder als ZIP heruntergeladen?" }, answer: { en: "Each page downloads as a separate image. Use a separate tool to ZIP them if needed.", zh: "每页作为单独图片下载。如需打包 ZIP，请使用其他工具。", ja: "各ページは個別の画像としてダウンロードされます。ZIP にする場合は別のツールを使ってください。", es: "Cada página se descarga como una imagen separada. Usa otra herramienta para comprimirlas en ZIP si lo necesitas.", pt: "Cada página é baixada como uma imagem separada. Use outra ferramenta para compactá-las em ZIP, se necessário.", fr: "Chaque page se télécharge comme une image séparée. Utilisez un autre outil pour les zipper si nécessaire.", de: "Jede Seite wird als separates Bild heruntergeladen. Verwenden Sie ggf. ein anderes Tool zum ZIPen." } },
    ]
  },
  {
    slug: "image/convert", category: "image", icon: "RefreshCw",
    name: { en: "Convert Image", zh: "转换格式", ja: "形式変換", es: "Convertir Formato", pt: "Converter Formato", fr: "Convertir Format", de: "Format konvertieren" },
    description: { en: "Convert images between JPG, PNG, WebP, BMP", zh: "在 JPG、PNG、WebP、BMP 之间转换", ja: "JPG、PNG、WebP、BMP 間で画像を変換", es: "Convertir entre JPG, PNG, WebP, BMP", pt: "Converter entre JPG, PNG, WebP, BMP", fr: "Convertir entre JPG, PNG, WebP, BMP", de: "Zwischen JPG, PNG, WebP, BMP konvertieren" },
    faq: [
      { question: { en: "Which format is best for the web?", zh: "网页用哪个格式最好？", ja: "ウェブにはどの形式が最適ですか？", es: "¿Qué formato es mejor para la web?", pt: "Qual formato é melhor para a web?", fr: "Quel format est le meilleur pour le web ?", de: "Welches Format ist am besten fürs Web?" }, answer: { en: "WebP offers the best size/quality ratio for web. PNG for transparency. JPEG for photos. Avoid BMP (large files).", zh: "WebP 大小/质量比最佳，需要透明用 PNG，照片用 JPEG。避免 BMP（文件太大）。", ja: "WebP はサイズ/品質比が最高です。透明には PNG、写真には JPEG。BMP は避けてください（ファイルが大きすぎます）。", es: "WebP ofrece la mejor relación tamaño/calidad para la web. PNG para transparencia. JPEG para fotos. Evita BMP (archivos grandes).", pt: "WebP oferece a melhor relação tamanho/qualidade para a web. PNG para transparência. JPEG para fotos. Evite BMP (arquivos grandes).", fr: "WebP offre le meilleur rapport taille/qualité pour le web. PNG pour la transparence. JPEG pour les photos. Évitez BMP (fichiers volumineux).", de: "WebP bietet das beste Größe-Qualität-Verhältnis fürs Web. PNG für Transparenz. JPEG für Fotos. BMP vermeiden (große Dateien)." } },
      { question: { en: "Will image quality be lost when converting?", zh: "转换格式会损失图片质量吗？", ja: "形式を変換すると画質は落ちますか？", es: "¿Se pierde calidad al convertir?", pt: "A qualidade é perdida ao converter?", fr: "La qualité est-elle perdue lors de la conversion ?", de: "Geht Bildqualität beim Konvertieren verloren?" }, answer: { en: "Converting to JPEG is lossy (slight loss). Converting to PNG or WebP is lossless. Converting between lossless formats is also lossless.", zh: "转 JPEG 有损（轻微损失）。转 PNG 或 WebP 无损。无损格式之间转换也是无损。", ja: "JPEG への変換は非可逆（わずかな損失）。PNG や WebP への変換は可逆。可逆形式間の変換も可逆です。", es: "Convertir a JPEG es con pérdida (ligera pérdida). Convertir a PNG o WebP es sin pérdida. Convertir entre formatos sin pérdida también es sin pérdida.", pt: "Converter para JPEG é com perdas (perda leve). Converter para PNG ou WebP é sem perdas. Converter entre formatos sem perdas também é sem perdas.", fr: "Convertir en JPEG est avec perte (légère perte). Convertir en PNG ou WebP est sans perte. Convertir entre formats sans perte est également sans perte.", de: "Konvertierung zu JPEG ist verlustbehaftet (geringer Verlust). Zu PNG oder WebP ist verlustfrei. Zwischen verlustfreien Formaten ist ebenfalls verlustfrei." } },
      { question: { en: "Can I convert multiple images at once?", zh: "可以一次转换多张图片吗？", ja: "複数の画像を一括変換できますか？", es: "¿Puedo convertir varias imágenes a la vez?", pt: "Posso converter várias imagens de uma vez?", fr: "Puis-je convertir plusieurs images à la fois ?", de: "Kann ich mehrere Bilder gleichzeitig konvertieren?" }, answer: { en: "Yes, the tool supports batch conversion. Drag multiple images and they'll all be converted to your selected format.", zh: "可以，支持批量转换。拖入多张图片，它们会全部转换为你选择的格式。", ja: "はい、一括変換に対応しています。複数の画像をドラッグすると、選択した形式にすべて変換されます。", es: "Sí, la herramienta admite conversión por lotes. Arrastra varias imágenes y todas se convertirán al formato seleccionado.", pt: "Sim, a ferramenta suporta conversão em lote. Arraste várias imagens e todas serão convertidas para o formato selecionado.", fr: "Oui, l'outil prend en charge la conversion par lots. Faites glisser plusieurs images et elles seront toutes converties dans le format sélectionné.", de: "Ja, das Tool unterstützt Stapelkonvertierung. Ziehen Sie mehrere Bilder herein und alle werden in Ihr gewähltes Format konvertiert." } },
    ]
  },
  { slug: "pdf/image-to-pdf", category: "pdf", icon: "FileImage", name: { en: "Image to PDF", zh: "图片转 PDF", ja: "画像を PDF に", es: "Imagen a PDF", pt: "Imagem para PDF", fr: "Image en PDF", de: "Bild zu PDF" }, description: { en: "Convert images to a single PDF file", zh: "将图片转换为单个 PDF 文件", ja: "画像を 1 つの PDF ファイルに変換", es: "Convertir imágenes a un solo PDF", pt: "Converter imagens em um único PDF", fr: "Convertir des images en un seul PDF", de: "Bilder in eine PDF-Datei konvertieren" } },
  { slug: "pdf/add-watermark", category: "pdf", icon: "Stamp", name: { en: "Add Watermark", zh: "添加水印", ja: "透かし追加", es: "Añadir Marca de Agua", pt: "Adicionar Marca D'água", fr: "Ajouter Filigrane", de: "Wasserzeichen hinzufügen" }, description: { en: "Add text watermark to PDF pages", zh: "向 PDF 页面添加文本水印", ja: "PDF ページにテキスト透かしを追加", es: "Añadir marca de agua de texto a páginas PDF", pt: "Adicionar marca d'água de texto a páginas PDF", fr: "Ajouter un filigrane de texte aux pages PDF", de: "Textwasserzeichen zu PDF-Seiten hinzufügen" } },
  { slug: "pdf/rotate", category: "pdf", icon: "RotateCw", name: { en: "Rotate PDF", zh: "旋转 PDF", ja: "PDF 回転", es: "Rotar PDF", pt: "Girar PDF", fr: "Pivoter PDF", de: "PDF drehen" }, description: { en: "Rotate PDF pages by 90, 180 or 270 degrees", zh: "将 PDF 页面旋转 90、180 或 270 度", ja: "PDF ページを 90、180、270 度回転", es: "Rotar páginas PDF 90, 180 o 270 grados", pt: "Girar páginas PDF em 90, 180 ou 270 graus", fr: "Pivoter les pages PDF de 90, 180 ou 270 degrés", de: "PDF-Seiten um 90, 180 oder 270 Grad drehen" } },
  { slug: "pdf/extract-text", category: "pdf", icon: "FileText", name: { en: "Extract Text", zh: "提取文本", ja: "テキスト抽出", es: "Extraer Texto", pt: "Extrair Texto", fr: "Extraire Texte", de: "Text extrahieren" }, description: { en: "Extract text content from PDF as plain text", zh: "从 PDF 中提取纯文本内容", ja: "PDF からテキストを抽出", es: "Extraer texto del PDF como texto plano", pt: "Extrair texto do PDF como texto simples", fr: "Extraire le texte du PDF en texte brut", de: "Text aus PDF extrahieren" } },
  { slug: "pdf/reorder", category: "pdf", icon: "ListOrdered", name: { en: "Reorder Pages", zh: "重排页面", ja: "ページ並び替え", es: "Reordenar Páginas", pt: "Reordenar Páginas", fr: "Réorganiser Pages", de: "Seiten neu anordnen" }, description: { en: "Drag and drop to reorder PDF pages", zh: "拖放以重新排序 PDF 页面", ja: "ドラッグ&ドロップで PDF ページを並べ替え", es: "Arrastra y suelta para reordenar páginas PDF", pt: "Arraste e solte para reordenar páginas PDF", fr: "Glissez-déposez pour réorganiser les pages PDF", de: "PDF-Seiten per Drag & Drop neu anordnen" } },

  // Image
  { slug: "image/compress", category: "image", icon: "Minimize2", name: { en: "Compress Image", zh: "压缩图片", ja: "画像圧縮", es: "Comprimir Imagen", pt: "Comprimir Imagem", fr: "Compresser Image", de: "Bild komprimieren" }, description: { en: "Reduce image file size with quality control", zh: "在控制质量的同时减小图片大小", ja: "画質を制御しながら画像サイズを縮小", es: "Reducir el tamaño de la imagen con control de calidad", pt: "Reduzir o tamanho da imagem com controle de qualidade", fr: "Réduire la taille de l'image avec contrôle qualité", de: "Bildgröße mit Qualitätskontrolle reduzieren" } },
  { slug: "image/resize", category: "image", icon: "Maximize2", name: { en: "Resize Image", zh: "调整大小", ja: "リサイズ", es: "Redimensionar", pt: "Redimensionar", fr: "Redimensionner", de: "Bild skalieren" }, description: { en: "Resize images to any width and height", zh: "将图片调整为任意宽度和高度", ja: "画像を任意の幅と高さにリサイズ", es: "Redimensionar imágenes a cualquier ancho y alto", pt: "Redimensionar imagens para qualquer largura e altura", fr: "Redimensionner des images à toute largeur et hauteur", de: "Bilder auf beliebige Breite und Höhe skalieren" } },
  { slug: "image/crop", category: "image", icon: "Crop", name: { en: "Crop Image", zh: "裁剪图片", ja: "画像切り取り", es: "Recortar Imagen", pt: "Recortar Imagem", fr: "Recadrer Image", de: "Bild zuschneiden" }, description: { en: "Crop images to remove unwanted areas", zh: "裁剪图片以去除不需要的区域", ja: "不要な領域を削除するために画像を切り取る", es: "Recortar imágenes para eliminar áreas no deseadas", pt: "Recortar imagens para remover áreas indesejadas", fr: "Recadrer des images pour supprimer les zones inutiles", de: "Bilder zuschneiden, um unerwünschte Bereiche zu entfernen" } },
  { slug: "image/convert", category: "image", icon: "RefreshCw", name: { en: "Convert Image", zh: "转换格式", ja: "形式変換", es: "Convertir Formato", pt: "Converter Formato", fr: "Convertir Format", de: "Format konvertieren" }, description: { en: "Convert images between JPG, PNG, WebP, BMP", zh: "在 JPG、PNG、WebP、BMP 之间转换", ja: "JPG、PNG、WebP、BMP 間で画像を変換", es: "Convertir entre JPG, PNG, WebP, BMP", pt: "Converter entre JPG, PNG, WebP, BMP", fr: "Convertir entre JPG, PNG, WebP, BMP", de: "Zwischen JPG, PNG, WebP, BMP konvertieren" } },
  { slug: "image/add-watermark", category: "image", icon: "Stamp", name: { en: "Add Watermark", zh: "添加水印", ja: "透かし追加", es: "Marca de Agua", pt: "Marca D'água", fr: "Filigrane", de: "Wasserzeichen" }, description: { en: "Add text watermark to images", zh: "向图片添加文本水印", ja: "画像にテキスト透かしを追加", es: "Añadir marca de agua de texto a imágenes", pt: "Adicionar marca d'água de texto a imagens", fr: "Ajouter un filigrane de texte aux images", de: "Textwasserzeichen zu Bildern hinzufügen" } },

  // Text
  { slug: "text/char-count", category: "text", icon: "Hash", name: { en: "Character Count", zh: "字符统计", ja: "文字数カウント", es: "Contar Caracteres", pt: "Contar Caracteres", fr: "Compter Caractères", de: "Zeichen zählen" }, description: { en: "Count characters, words, lines and bytes", zh: "统计字符、单词、行数和字节", ja: "文字、単語、行、バイトをカウント", es: "Contar caracteres, palabras, líneas y bytes", pt: "Contar caracteres, palavras, linhas e bytes", fr: "Compter caractères, mots, lignes et octets", de: "Zeichen, Wörter, Zeilen und Bytes zählen" } },
  { slug: "text/case-convert", category: "text", icon: "CaseSensitive", name: { en: "Case Converter", zh: "大小写转换", ja: "大文字小文字変換", es: "Convertir Mayúsculas", pt: "Converter Maiúsculas", fr: "Convertir Casse", de: "Groß-/Kleinschreibung" }, description: { en: "Convert text to upper, lower, title, sentence case", zh: "将文本转换为大写、小写、标题、句首大写", ja: "テキストを大文字、小文字、タイトル文、 文頭大文字に変換", es: "Convertir texto a mayúsculas, minúsculas, título, oración", pt: "Converter texto para maiúsculas, minúsculas, título, frase", fr: "Convertir texte en majuscules, minuscules, titre, phrase", de: "Text in Groß-, Klein-, Titel- oder Satzkleinbuchstaben umwandeln" } },
  { slug: "text/duplicate", category: "text", icon: "CopyX", name: { en: "Remove Duplicates", zh: "去除重复", ja: "重複削除", es: "Eliminar Duplicados", pt: "Remover Duplicados", fr: "Supprimer Doublons", de: "Duplikate entfernen" }, description: { en: "Remove duplicate lines from text", zh: "从文本中删除重复行", ja: "テキストから重複行を削除", es: "Eliminar líneas duplicadas del texto", pt: "Remover linhas duplicadas do texto", fr: "Supprimer les lignes en double du texte", de: "Doppelte Zeilen aus Text entfernen" } },
  { slug: "text/diff", category: "text", icon: "GitCompare", name: { en: "Text Diff", zh: "文本对比", ja: "テキスト比較", es: "Comparar Texto", pt: "Comparar Texto", fr: "Comparer Texte", de: "Text vergleichen" }, description: { en: "Compare two texts and show differences", zh: "比较两个文本并显示差异", ja: "2 つのテキストを比較し、違いを表示", es: "Comparar dos textos y mostrar diferencias", pt: "Comparar dois textos e mostrar diferenças", fr: "Comparer deux textes et afficher les différences", de: "Zwei Texte vergleichen und Unterschiede anzeigen" } },
  { slug: "text/regex", category: "text", icon: "Regex", name: { en: "Regex Tester", zh: "正则测试", ja: "正規表現テスター", es: "Probador Regex", pt: "Testador Regex", fr: "Testeur Regex", de: "Regex-Tester" }, description: { en: "Test and debug regular expressions", zh: "测试和调试正则表达式", ja: "正規表現のテストとデバッグ", es: "Probar y depurar expresiones regulares", pt: "Testar e depurar expressões regulares", fr: "Tester et déboguer des expressions régulières", de: "Reguläre Ausdrücke testen und debuggen" } },

  // Unit
  { slug: "unit/length", category: "unit", icon: "Ruler", name: { en: "Length Converter", zh: "长度换算", ja: "長さ変換", es: "Conversor de Longitud", pt: "Conversor de Comprimento", fr: "Convertisseur de Longueur", de: "Längenumrechner" }, description: { en: "Convert between meters, feet, inches, miles and more", zh: "米、英尺、英寸、英里等单位换算", ja: "メートル、フィート、インチ、マイルなどの変換", es: "Convertir entre metros, pies, pulgadas, millas y más", pt: "Converter entre metros, pés, polegadas, milhas e mais", fr: "Convertir entre mètres, pieds, pouces, miles et plus", de: "Zwischen Meter, Fuß, Zoll, Meilen und mehr umrechnen" } },
  { slug: "unit/weight", category: "unit", icon: "Weight", name: { en: "Weight Converter", zh: "重量换算", ja: "重さ変換", es: "Conversor de Peso", pt: "Conversor de Peso", fr: "Convertisseur de Poids", de: "Gewichtsumrechner" }, description: { en: "Convert between kg, lbs, oz, grams and more", zh: "千克、磅、盎司、克等单位换算", ja: "キログラム、ポンド、オンス、グラムなどの変換", es: "Convertir entre kg, lbs, oz, gramos y más", pt: "Converter entre kg, lbs, oz, gramas e mais", fr: "Convertir entre kg, lbs, oz, grammes et plus", de: "Zwischen kg, lbs, oz, Gramm und mehr umrechnen" } },
  { slug: "unit/temperature", category: "unit", icon: "Thermometer", name: { en: "Temperature Converter", zh: "温度换算", ja: "温度変換", es: "Conversor de Temperatura", pt: "Conversor de Temperatura", fr: "Convertisseur de Température", de: "Temperaturumrechner" }, description: { en: "Convert between Celsius, Fahrenheit, Kelvin", zh: "摄氏、华氏、开尔文之间转换", ja: "摂氏、華氏、ケルビン間で変換", es: "Convertir entre Celsius, Fahrenheit, Kelvin", pt: "Converter entre Celsius, Fahrenheit, Kelvin", fr: "Convertir entre Celsius, Fahrenheit, Kelvin", de: "Zwischen Celsius, Fahrenheit, Kelvin umrechnen" } },
  { slug: "unit/area", category: "unit", icon: "Square", name: { en: "Area Converter", zh: "面积换算", ja: "面積変換", es: "Conversor de Área", pt: "Conversor de Área", fr: "Convertisseur de Surface", de: "Flächenumrechner" }, description: { en: "Convert between m², ft², acres, hectares and more", zh: "平方米、平方英尺、英亩、公顷等单位换算", ja: "平方メートル、平方フィート、エーカー、ヘクタールなど", es: "Convertir entre m², ft², acres, hectáreas y más", pt: "Converter entre m², ft², acres, hectares e mais", fr: "Convertir entre m², ft², acres, hectares et plus", de: "Zwischen m², ft², Acres, Hektar und mehr umrechnen" } },
  { slug: "unit/volume", category: "unit", icon: "Beaker", name: { en: "Volume Converter", zh: "体积换算", ja: "体積変換", es: "Conversor de Volumen", pt: "Conversor de Volume", fr: "Convertisseur de Volume", de: "Volumenumrechner" }, description: { en: "Convert between liters, gallons, cups, ml and more", zh: "升、加仑、杯、毫升等单位换算", ja: "リットル、ガロン、カップ、ミリリットルなど", es: "Convertir entre litros, galones, tazas, ml y más", pt: "Converter entre litros, galões, copos, ml e mais", fr: "Convertir entre litres, gallons, tasses, ml et plus", de: "Zwischen Liter, Gallonen, Tassen, ml und mehr umrechnen" } },
  { slug: "unit/speed", category: "unit", icon: "Gauge", name: { en: "Speed Converter", zh: "速度换算", ja: "速度変換", es: "Conversor de Velocidad", pt: "Conversor de Velocidade", fr: "Convertisseur de Vitesse", de: "Geschwindigkeitsumrechner" }, description: { en: "Convert between km/h, mph, m/s, knots and more", zh: "公里/小时、英里/小时、米/秒、节等单位换算", ja: "km/h、mph、m/s、ノットなどの変換", es: "Convertir entre km/h, mph, m/s, nudos y más", pt: "Converter entre km/h, mph, m/s, nós e mais", fr: "Convertir entre km/h, mph, m/s, nœuds et plus", de: "Zwischen km/h, mph, m/s, Knoten und mehr umrechnen" } },
  { slug: "unit/data", category: "unit", icon: "HardDrive", name: { en: "Data Storage Converter", zh: "数据存储换算", ja: "データ容量変換", es: "Conversor de Almacenamiento", pt: "Conversor de Armazenamento", fr: "Convertisseur de Stockage", de: "Datenspeicher-Umrechner" }, description: { en: "Convert between B, KB, MB, GB, TB, PB", zh: "B、KB、MB、GB、TB、PB 之间转换", ja: "B、KB、MB、GB、TB、PB 間で変換", es: "Convertir entre B, KB, MB, GB, TB, PB", pt: "Converter entre B, KB, MB, GB, TB, PB", fr: "Convertir entre B, KB, MB, GB, TB, PB", de: "Zwischen B, KB, MB, GB, TB, PB umrechnen" } },
  { slug: "unit/time", category: "unit", icon: "Clock", name: { en: "Time Converter", zh: "时间换算", ja: "時間変換", es: "Conversor de Tiempo", pt: "Conversor de Tempo", fr: "Convertisseur de Temps", de: "Zeitumrechner" }, description: { en: "Convert between seconds, minutes, hours, days, years", zh: "秒、分钟、小时、天、年之间转换", ja: "秒、分、時間、日、年の間で変換", es: "Convertir entre segundos, minutos, horas, días, años", pt: "Converter entre segundos, minutos, horas, dias, anos", fr: "Convertir entre secondes, minutes, heures, jours, années", de: "Zwischen Sekunden, Minuten, Stunden, Tagen, Jahren umrechnen" } },

  // Color
  { slug: "color/picker", category: "color", icon: "Pipette", name: { en: "Color Picker", zh: "取色器", ja: "カラーピッカー", es: "Selector de Color", pt: "Seletor de Cor", fr: "Sélecteur de Couleur", de: "Farbwähler" }, description: { en: "Pick colors from images and get HEX, RGB, HSL", zh: "从图片中取色，获取 HEX、RGB、HSL", ja: "画像から色を取得し、HEX、RGB、HSL を取得", es: "Elegir colores de imágenes y obtener HEX, RGB, HSL", pt: "Escolher cores de imagens e obter HEX, RGB, HSL", fr: "Choisir des couleurs dans des images et obtenir HEX, RGB, HSL", de: "Farben aus Bildern wählen und HEX, RGB, HSL erhalten" } },
  { slug: "color/hex-rgb", category: "color", icon: "Palette", name: { en: "HEX/RGB Converter", zh: "HEX/RGB 转换", ja: "HEX/RGB 変換", es: "Conversor HEX/RGB", pt: "Conversor HEX/RGB", fr: "Convertisseur HEX/RGB", de: "HEX/RGB-Konverter" }, description: { en: "Convert between HEX, RGB, HSL and CMYK", zh: "HEX、RGB、HSL、CMYK 之间转换", ja: "HEX、RGB、HSL、CMYK 間で変換", es: "Convertir entre HEX, RGB, HSL y CMYK", pt: "Converter entre HEX, RGB, HSL e CMYK", fr: "Convertir entre HEX, RGB, HSL et CMYK", de: "Zwischen HEX, RGB, HSL und CMYK konvertieren" } },
  { slug: "color/palette", category: "color", icon: "SwatchBook", name: { en: "Palette Generator", zh: "色板生成", ja: "パレット生成", es: "Generador de Paleta", pt: "Gerador de Paleta", fr: "Générateur de Palette", de: "Palettengenerator" }, description: { en: "Generate harmonious color palettes", zh: "生成和谐的颜色搭配", ja: "調和のとれたカラーパレットを生成", es: "Generar paletas de colores armoniosas", pt: "Gerar paletas de cores harmoniosas", fr: "Générer des palettes de couleurs harmonieuses", de: "Harmonische Farbpaletten generieren" } },

  // Crypto
  { slug: "crypto/hash", category: "crypto", icon: "Lock", name: { en: "Hash Generator", zh: "哈希生成", ja: "ハッシュ生成", es: "Generador de Hash", pt: "Gerador de Hash", fr: "Générateur de Hash", de: "Hash-Generator" }, description: { en: "Generate MD5, SHA-1, SHA-256, SHA-512 hashes", zh: "生成 MD5、SHA-1、SHA-256、SHA-512 哈希", ja: "MD5、SHA-1、SHA-256、SHA-512 ハッシュを生成", es: "Generar hashes MD5, SHA-1, SHA-256, SHA-512", pt: "Gerar hashes MD5, SHA-1, SHA-256, SHA-512", fr: "Générer des hashes MD5, SHA-1, SHA-256, SHA-512", de: "MD5, SHA-1, SHA-256, SHA-512 Hashes generieren" } },
  { slug: "crypto/base64", category: "crypto", icon: "Binary", name: { en: "Base64 Encode/Decode", zh: "Base64 编解码", ja: "Base64 エンコード/デコード", es: "Codificar/Decodificar Base64", pt: "Codificar/Decodificar Base64", fr: "Encoder/Décoder Base64", de: "Base64 kodieren/dekodieren" }, description: { en: "Encode and decode Base64 strings", zh: "Base64 字符串的编码和解码", ja: "Base64 文字列のエンコードとデコード", es: "Codificar y decodificar cadenas Base64", pt: "Codificar e decodificar strings Base64", fr: "Encoder et décoder des chaînes Base64", de: "Base64-Strings kodieren und dekodieren" } },
  { slug: "crypto/url-encode", category: "crypto", icon: "Link", name: { en: "URL Encode/Decode", zh: "URL 编解码", ja: "URL エンコード/デコード", es: "Codificar/Decodificar URL", pt: "Codificar/Decodificar URL", fr: "Encoder/Décoder URL", de: "URL kodieren/dekodieren" }, description: { en: "Encode and decode URL-encoded strings", zh: "URL 编码字符串的编码和解码", ja: "URL エンコード文字列のエンコードとデコード", es: "Codificar y decodificar cadenas URL-encoded", pt: "Codificar e decodificar strings URL-encoded", fr: "Encoder et décoder des chaînes URL-encoded", de: "URL-codierte Strings kodieren und dekodieren" } },
  { slug: "crypto/uuid", category: "crypto", icon: "Fingerprint", name: { en: "UUID Generator", zh: "UUID 生成", ja: "UUID 生成", es: "Generador UUID", pt: "Gerador UUID", fr: "Générateur UUID", de: "UUID-Generator" }, description: { en: "Generate UUID v1 and v4 identifiers", zh: "生成 UUID v1 和 v4 标识符", ja: "UUID v1 および v4 識別子を生成", es: "Generar identificadores UUID v1 y v4", pt: "Gerar identificadores UUID v1 e v4", fr: "Générer des identifiants UUID v1 et v4", de: "UUID v1 und v4 Identifikatoren generieren" } },

  // Dev
  { slug: "dev/json-format", category: "dev", icon: "Braces", name: { en: "JSON Formatter", zh: "JSON 格式化", ja: "JSON フォーマッタ", es: "Formateador JSON", pt: "Formatador JSON", fr: "Formateur JSON", de: "JSON-Formatierer" }, description: { en: "Format, validate and beautify JSON", zh: "格式化、验证、美化 JSON", ja: "JSON のフォーマット、検証、整形", es: "Formatear, validar y embellecer JSON", pt: "Formatar, validar e embelezar JSON", fr: "Formater, valider et embellir JSON", de: "JSON formatieren, validieren und verschönern" } },
  { slug: "dev/timestamp", category: "dev", icon: "Timer", name: { en: "Timestamp Converter", zh: "时间戳转换", ja: "タイムスタンプ変換", es: "Conversor Timestamp", pt: "Conversor Timestamp", fr: "Convertisseur Timestamp", de: "Zeitstempel-Konverter" }, description: { en: "Convert between Unix timestamps and dates", zh: "Unix 时间戳和日期之间转换", ja: "Unix タイムスタンプと日付の間で変換", es: "Convertir entre timestamps Unix y fechas", pt: "Converter entre timestamps Unix e datas", fr: "Convertir entre timestamps Unix et dates", de: "Zwischen Unix-Zeitstempeln und Daten umrechnen" } },
  { slug: "dev/qrcode", category: "dev", icon: "QrCode", name: { en: "QR Code Generator", zh: "QR 码生成", ja: "QR コード生成", es: "Generador QR", pt: "Gerador QR", fr: "Générateur QR", de: "QR-Code-Generator" }, description: { en: "Generate QR codes from text or URLs", zh: "从文本或 URL 生成 QR 码", ja: "テキストまたは URL から QR コードを生成", es: "Generar códigos QR desde texto o URLs", pt: "Gerar códigos QR de texto ou URLs", fr: "Générer des codes QR à partir de texte ou d'URLs", de: "QR-Codes aus Text oder URLs generieren" } },
  { slug: "dev/password", category: "dev", icon: "Key", name: { en: "Password Generator", zh: "密码生成", ja: "パスワード生成", es: "Generador de Contraseña", pt: "Gerador de Senha", fr: "Générateur de Mot de Passe", de: "Passwort-Generator" }, description: { en: "Generate strong random passwords", zh: "生成强随机密码", ja: "強力なランダムパスワードを生成", es: "Generar contraseñas aleatorias seguras", pt: "Gerar senhas aleatórias fortes", fr: "Générer des mots de passe aléatoires forts", de: "Starke zufällige Passwörter generieren" } },

  // New tools (will be translated by subagent)
  { slug: "pdf/protect", category: "pdf", icon: "Lock", name: { en: "Protect PDF", zh: "Protect PDF", ja: "Protect PDF", es: "Protect PDF", pt: "Protect PDF", fr: "Protect PDF", de: "Protect PDF" }, description: { en: "Add password to PDF", zh: "Add password to PDF", ja: "Add password to PDF", es: "Add password to PDF", pt: "Add password to PDF", fr: "Add password to PDF", de: "Add password to PDF" } },

  { slug: "pdf/unlock", category: "pdf", icon: "LockOpen", name: { en: "Unlock PDF", zh: "Unlock PDF", ja: "Unlock PDF", es: "Unlock PDF", pt: "Unlock PDF", fr: "Unlock PDF", de: "Unlock PDF" }, description: { en: "Remove password from PDF", zh: "Remove password from PDF", ja: "Remove password from PDF", es: "Remove password from PDF", pt: "Remove password from PDF", fr: "Remove password from PDF", de: "Remove password from PDF" } },

  { slug: "pdf/page-numbers", category: "pdf", icon: "ListOrdered", name: { en: "Add Page Numbers", zh: "Add Page Numbers", ja: "Add Page Numbers", es: "Add Page Numbers", pt: "Add Page Numbers", fr: "Add Page Numbers", de: "Add Page Numbers" }, description: { en: "Stamp page numbers on PDF", zh: "Stamp page numbers on PDF", ja: "Stamp page numbers on PDF", es: "Stamp page numbers on PDF", pt: "Stamp page numbers on PDF", fr: "Stamp page numbers on PDF", de: "Stamp page numbers on PDF" } },

  { slug: "pdf/sign", category: "pdf", icon: "PenTool", name: { en: "Sign PDF", zh: "Sign PDF", ja: "Sign PDF", es: "Sign PDF", pt: "Sign PDF", fr: "Sign PDF", de: "Sign PDF" }, description: { en: "Draw or type signature on PDF", zh: "Draw or type signature on PDF", ja: "Draw or type signature on PDF", es: "Draw or type signature on PDF", pt: "Draw or type signature on PDF", fr: "Draw or type signature on PDF", de: "Draw or type signature on PDF" } },

  { slug: "pdf/metadata", category: "pdf", icon: "FileCog", name: { en: "Edit Metadata", zh: "Edit Metadata", ja: "Edit Metadata", es: "Edit Metadata", pt: "Edit Metadata", fr: "Edit Metadata", de: "Edit Metadata" }, description: { en: "Edit PDF title/author/subject", zh: "Edit PDF title/author/subject", ja: "Edit PDF title/author/subject", es: "Edit PDF title/author/subject", pt: "Edit PDF title/author/subject", fr: "Edit PDF title/author/subject", de: "Edit PDF title/author/subject" } },

  { slug: "pdf/header-footer", category: "pdf", icon: "Heading1", name: { en: "Header & Footer", zh: "Header & Footer", ja: "Header & Footer", es: "Header & Footer", pt: "Header & Footer", fr: "Header & Footer", de: "Header & Footer" }, description: { en: "Add header/footer with text", zh: "Add header/footer with text", ja: "Add header/footer with text", es: "Add header/footer with text", pt: "Add header/footer with text", fr: "Add header/footer with text", de: "Add header/footer with text" } },

  { slug: "pdf/compare", category: "pdf", icon: "GitCompare", name: { en: "Compare PDFs", zh: "Compare PDFs", ja: "Compare PDFs", es: "Compare PDFs", pt: "Compare PDFs", fr: "Compare PDFs", de: "Compare PDFs" }, description: { en: "Side-by-side PDF comparison", zh: "Side-by-side PDF comparison", ja: "Side-by-side PDF comparison", es: "Side-by-side PDF comparison", pt: "Side-by-side PDF comparison", fr: "Side-by-side PDF comparison", de: "Side-by-side PDF comparison" } },

  { slug: "pdf/cropPdf", category: "pdf", icon: "Crop", name: { en: "Crop PDF", zh: "Crop PDF", ja: "Crop PDF", es: "Crop PDF", pt: "Crop PDF", fr: "Crop PDF", de: "Crop PDF" }, description: { en: "Crop PDF page margins", zh: "Crop PDF page margins", ja: "Crop PDF page margins", es: "Crop PDF page margins", pt: "Crop PDF page margins", fr: "Crop PDF page margins", de: "Crop PDF page margins" } },

  { slug: "image/rotate", category: "image", icon: "RotateCw", name: { en: "Rotate Image", zh: "Rotate Image", ja: "Rotate Image", es: "Rotate Image", pt: "Rotate Image", fr: "Rotate Image", de: "Rotate Image" }, description: { en: "Rotate image by any angle", zh: "Rotate image by any angle", ja: "Rotate image by any angle", es: "Rotate image by any angle", pt: "Rotate image by any angle", fr: "Rotate image by any angle", de: "Rotate image by any angle" } },

  { slug: "image/flip", category: "image", icon: "FlipHorizontal2", name: { en: "Flip Image", zh: "Flip Image", ja: "Flip Image", es: "Flip Image", pt: "Flip Image", fr: "Flip Image", de: "Flip Image" }, description: { en: "Flip horizontal or vertical", zh: "Flip horizontal or vertical", ja: "Flip horizontal or vertical", es: "Flip horizontal or vertical", pt: "Flip horizontal or vertical", fr: "Flip horizontal or vertical", de: "Flip horizontal or vertical" } },

  { slug: "image/base64", category: "image", icon: "Code", name: { en: "Image to Base64", zh: "Image to Base64", ja: "Image to Base64", es: "Image to Base64", pt: "Image to Base64", fr: "Image to Base64", de: "Image to Base64" }, description: { en: "Convert image to Base64 data URL", zh: "Convert image to Base64 data URL", ja: "Convert image to Base64 data URL", es: "Convert image to Base64 data URL", pt: "Convert image to Base64 data URL", fr: "Convert image to Base64 data URL", de: "Convert image to Base64 data URL" } },

  { slug: "image/exif", category: "image", icon: "Eraser", name: { en: "Remove EXIF", zh: "Remove EXIF", ja: "Remove EXIF", es: "Remove EXIF", pt: "Remove EXIF", fr: "Remove EXIF", de: "Remove EXIF" }, description: { en: "Strip EXIF metadata from photos", zh: "Strip EXIF metadata from photos", ja: "Strip EXIF metadata from photos", es: "Strip EXIF metadata from photos", pt: "Strip EXIF metadata from photos", fr: "Strip EXIF metadata from photos", de: "Strip EXIF metadata from photos" } },

  { slug: "image/blur", category: "image", icon: "Droplet", name: { en: "Blur Image", zh: "Blur Image", ja: "Blur Image", es: "Blur Image", pt: "Blur Image", fr: "Blur Image", de: "Blur Image" }, description: { en: "Apply Gaussian blur to image", zh: "Apply Gaussian blur to image", ja: "Apply Gaussian blur to image", es: "Apply Gaussian blur to image", pt: "Apply Gaussian blur to image", fr: "Apply Gaussian blur to image", de: "Apply Gaussian blur to image" } },

  { slug: "image/upscale", category: "image", icon: "ZoomIn", name: { en: "Upscale Image", zh: "Upscale Image", ja: "Upscale Image", es: "Upscale Image", pt: "Upscale Image", fr: "Upscale Image", de: "Upscale Image" }, description: { en: "Upscale image 2x with smoothing", zh: "Upscale image 2x with smoothing", ja: "Upscale image 2x with smoothing", es: "Upscale image 2x with smoothing", pt: "Upscale image 2x with smoothing", fr: "Upscale image 2x with smoothing", de: "Upscale image 2x with smoothing" } },

  { slug: "image/meme", category: "image", icon: "Smile", name: { en: "Meme Generator", zh: "Meme Generator", ja: "Meme Generator", es: "Meme Generator", pt: "Meme Generator", fr: "Meme Generator", de: "Meme Generator" }, description: { en: "Add top/bottom text to image", zh: "Add top/bottom text to image", ja: "Add top/bottom text to image", es: "Add top/bottom text to image", pt: "Add top/bottom text to image", fr: "Add top/bottom text to image", de: "Add top/bottom text to image" } },

  { slug: "text/reverse", category: "text", icon: "Undo2", name: { en: "Reverse Text", zh: "Reverse Text", ja: "Reverse Text", es: "Reverse Text", pt: "Reverse Text", fr: "Reverse Text", de: "Reverse Text" }, description: { en: "Reverse text character order", zh: "Reverse text character order", ja: "Reverse text character order", es: "Reverse text character order", pt: "Reverse text character order", fr: "Reverse text character order", de: "Reverse text character order" } },

  { slug: "text/sort", category: "text", icon: "ArrowUpDown", name: { en: "Sort Lines", zh: "Sort Lines", ja: "Sort Lines", es: "Sort Lines", pt: "Sort Lines", fr: "Sort Lines", de: "Sort Lines" }, description: { en: "Sort lines alphabetically or numerically", zh: "Sort lines alphabetically or numerically", ja: "Sort lines alphabetically or numerically", es: "Sort lines alphabetically or numerically", pt: "Sort lines alphabetically or numerically", fr: "Sort lines alphabetically or numerically", de: "Sort lines alphabetically or numerically" } },

  { slug: "text/lorem", category: "text", icon: "FileText", name: { en: "Lorem Ipsum", zh: "Lorem Ipsum", ja: "Lorem Ipsum", es: "Lorem Ipsum", pt: "Lorem Ipsum", fr: "Lorem Ipsum", de: "Lorem Ipsum" }, description: { en: "Generate placeholder text", zh: "Generate placeholder text", ja: "Generate placeholder text", es: "Generate placeholder text", pt: "Generate placeholder text", fr: "Generate placeholder text", de: "Generate placeholder text" } },

  { slug: "text/markdown", category: "text", icon: "FileCode", name: { en: "Markdown Preview", zh: "Markdown Preview", ja: "Markdown Preview", es: "Markdown Preview", pt: "Markdown Preview", fr: "Markdown Preview", de: "Markdown Preview" }, description: { en: "Live markdown rendering", zh: "Live markdown rendering", ja: "Live markdown rendering", es: "Live markdown rendering", pt: "Live markdown rendering", fr: "Live markdown rendering", de: "Live markdown rendering" } },

  { slug: "text/fancy", category: "text", icon: "Sparkles", name: { en: "Fancy Text", zh: "Fancy Text", ja: "Fancy Text", es: "Fancy Text", pt: "Fancy Text", fr: "Fancy Text", de: "Fancy Text" }, description: { en: "Unicode stylized text", zh: "Unicode stylized text", ja: "Unicode stylized text", es: "Unicode stylized text", pt: "Unicode stylized text", fr: "Unicode stylized text", de: "Unicode stylized text" } },

  { slug: "text/rot13", category: "text", icon: "Lock", name: { en: "ROT13", zh: "ROT13", ja: "ROT13", es: "ROT13", pt: "ROT13", fr: "ROT13", de: "ROT13" }, description: { en: "ROT13 cipher encode/decode", zh: "ROT13 cipher encode/decode", ja: "ROT13 cipher encode/decode", es: "ROT13 cipher encode/decode", pt: "ROT13 cipher encode/decode", fr: "ROT13 cipher encode/decode", de: "ROT13 cipher encode/decode" } },

  { slug: "unit/pressure", category: "unit", icon: "Gauge", name: { en: "Pressure Converter", zh: "Pressure Converter", ja: "Pressure Converter", es: "Pressure Converter", pt: "Pressure Converter", fr: "Pressure Converter", de: "Pressure Converter" }, description: { en: "Convert between Pa, bar, psi, atm", zh: "Convert between Pa, bar, psi, atm", ja: "Convert between Pa, bar, psi, atm", es: "Convert between Pa, bar, psi, atm", pt: "Convert between Pa, bar, psi, atm", fr: "Convert between Pa, bar, psi, atm", de: "Convert between Pa, bar, psi, atm" } },

  { slug: "unit/energy", category: "unit", icon: "Zap", name: { en: "Energy Converter", zh: "Energy Converter", ja: "Energy Converter", es: "Energy Converter", pt: "Energy Converter", fr: "Energy Converter", de: "Energy Converter" }, description: { en: "Convert J, kJ, cal, kcal, Wh, kWh", zh: "Convert J, kJ, cal, kcal, Wh, kWh", ja: "Convert J, kJ, cal, kcal, Wh, kWh", es: "Convert J, kJ, cal, kcal, Wh, kWh", pt: "Convert J, kJ, cal, kcal, Wh, kWh", fr: "Convert J, kJ, cal, kcal, Wh, kWh", de: "Convert J, kJ, cal, kcal, Wh, kWh" } },

  { slug: "unit/power", category: "unit", icon: "Power", name: { en: "Power Converter", zh: "Power Converter", ja: "Power Converter", es: "Power Converter", pt: "Power Converter", fr: "Power Converter", de: "Power Converter" }, description: { en: "Watt, kW, MW, HP conversions", zh: "Watt, kW, MW, HP conversions", ja: "Watt, kW, MW, HP conversions", es: "Watt, kW, MW, HP conversions", pt: "Watt, kW, MW, HP conversions", fr: "Watt, kW, MW, HP conversions", de: "Watt, kW, MW, HP conversions" } },

  { slug: "unit/fuel", category: "unit", icon: "Fuel", name: { en: "Fuel Economy", zh: "Fuel Economy", ja: "Fuel Economy", es: "Fuel Economy", pt: "Fuel Economy", fr: "Fuel Economy", de: "Fuel Economy" }, description: { en: "MPG, L/100km, km/L", zh: "MPG, L/100km, km/L", ja: "MPG, L/100km, km/L", es: "MPG, L/100km, km/L", pt: "MPG, L/100km, km/L", fr: "MPG, L/100km, km/L", de: "MPG, L/100km, km/L" } },

  { slug: "color/gradient", category: "color", icon: "PaintBucket", name: { en: "CSS Gradient", zh: "CSS Gradient", ja: "CSS Gradient", es: "CSS Gradient", pt: "CSS Gradient", fr: "CSS Gradient", de: "CSS Gradient" }, description: { en: "Visual CSS gradient generator", zh: "Visual CSS gradient generator", ja: "Visual CSS gradient generator", es: "Visual CSS gradient generator", pt: "Visual CSS gradient generator", fr: "Visual CSS gradient generator", de: "Visual CSS gradient generator" } },

  { slug: "color/contrast", category: "color", icon: "Contrast", name: { en: "Contrast Checker", zh: "Contrast Checker", ja: "Contrast Checker", es: "Contrast Checker", pt: "Contrast Checker", fr: "Contrast Checker", de: "Contrast Checker" }, description: { en: "WCAG color contrast ratio", zh: "WCAG color contrast ratio", ja: "WCAG color contrast ratio", es: "WCAG color contrast ratio", pt: "WCAG color contrast ratio", fr: "WCAG color contrast ratio", de: "WCAG color contrast ratio" } },

  { slug: "color/mixer", category: "color", icon: "Blend", name: { en: "Color Mixer", zh: "Color Mixer", ja: "Color Mixer", es: "Color Mixer", pt: "Color Mixer", fr: "Color Mixer", de: "Color Mixer" }, description: { en: "Mix two colors to get result", zh: "Mix two colors to get result", ja: "Mix two colors to get result", es: "Mix two colors to get result", pt: "Mix two colors to get result", fr: "Mix two colors to get result", de: "Mix two colors to get result" } },

  { slug: "color/named", category: "color", icon: "Tag", name: { en: "Named Colors", zh: "Named Colors", ja: "Named Colors", es: "Named Colors", pt: "Named Colors", fr: "Named Colors", de: "Named Colors" }, description: { en: "Browse 140+ CSS named colors", zh: "Browse 140+ CSS named colors", ja: "Browse 140+ CSS named colors", es: "Browse 140+ CSS named colors", pt: "Browse 140+ CSS named colors", fr: "Browse 140+ CSS named colors", de: "Browse 140+ CSS named colors" } },

  { slug: "crypto/jwt", category: "crypto", icon: "KeyRound", name: { en: "JWT Decoder", zh: "JWT Decoder", ja: "JWT Decoder", es: "JWT Decoder", pt: "JWT Decoder", fr: "JWT Decoder", de: "JWT Decoder" }, description: { en: "Decode JSON Web Tokens", zh: "Decode JSON Web Tokens", ja: "Decode JSON Web Tokens", es: "Decode JSON Web Tokens", pt: "Decode JSON Web Tokens", fr: "Decode JSON Web Tokens", de: "Decode JSON Web Tokens" } },

  { slug: "crypto/hmac", category: "crypto", icon: "Fingerprint", name: { en: "HMAC Generator", zh: "HMAC Generator", ja: "HMAC Generator", es: "HMAC Generator", pt: "HMAC Generator", fr: "HMAC Generator", de: "HMAC Generator" }, description: { en: "Generate HMAC-SHA256 signatures", zh: "Generate HMAC-SHA256 signatures", ja: "Generate HMAC-SHA256 signatures", es: "Generate HMAC-SHA256 signatures", pt: "Generate HMAC-SHA256 signatures", fr: "Generate HMAC-SHA256 signatures", de: "Generate HMAC-SHA256 signatures" } },

  { slug: "crypto/checksum", category: "crypto", icon: "FileLock2", name: { en: "File Checksum", zh: "File Checksum", ja: "File Checksum", es: "File Checksum", pt: "File Checksum", fr: "File Checksum", de: "File Checksum" }, description: { en: "Compute MD5/SHA-256 file hash", zh: "Compute MD5/SHA-256 file hash", ja: "Compute MD5/SHA-256 file hash", es: "Compute MD5/SHA-256 file hash", pt: "Compute MD5/SHA-256 file hash", fr: "Compute MD5/SHA-256 file hash", de: "Compute MD5/SHA-256 file hash" } },

  { slug: "dev/yamlJson", category: "dev", icon: "FileJson", name: { en: "YAML ⇄ JSON", zh: "YAML ⇄ JSON", ja: "YAML ⇄ JSON", es: "YAML ⇄ JSON", pt: "YAML ⇄ JSON", fr: "YAML ⇄ JSON", de: "YAML ⇄ JSON" }, description: { en: "Convert between YAML and JSON", zh: "Convert between YAML and JSON", ja: "Convert between YAML and JSON", es: "Convert between YAML and JSON", pt: "Convert between YAML and JSON", fr: "Convert between YAML and JSON", de: "Convert between YAML and JSON" } },

  { slug: "dev/csv", category: "dev", icon: "Table", name: { en: "CSV ⇄ JSON", zh: "CSV ⇄ JSON", ja: "CSV ⇄ JSON", es: "CSV ⇄ JSON", pt: "CSV ⇄ JSON", fr: "CSV ⇄ JSON", de: "CSV ⇄ JSON" }, description: { en: "Convert CSV to/from JSON", zh: "Convert CSV to/from JSON", ja: "Convert CSV to/from JSON", es: "Convert CSV to/from JSON", pt: "Convert CSV to/from JSON", fr: "Convert CSV to/from JSON", de: "Convert CSV to/from JSON" } },

  { slug: "dev/sql", category: "dev", icon: "Database", name: { en: "SQL Formatter", zh: "SQL Formatter", ja: "SQL Formatter", es: "SQL Formatter", pt: "SQL Formatter", fr: "SQL Formatter", de: "SQL Formatter" }, description: { en: "Format and beautify SQL queries", zh: "Format and beautify SQL queries", ja: "Format and beautify SQL queries", es: "Format and beautify SQL queries", pt: "Format and beautify SQL queries", fr: "Format and beautify SQL queries", de: "Format and beautify SQL queries" } },

  { slug: "dev/xml", category: "dev", icon: "FileCode2", name: { en: "XML Formatter", zh: "XML Formatter", ja: "XML Formatter", es: "XML Formatter", pt: "XML Formatter", fr: "XML Formatter", de: "XML Formatter" }, description: { en: "Format and validate XML", zh: "Format and validate XML", ja: "Format and validate XML", es: "Format and validate XML", pt: "Format and validate XML", fr: "Format and validate XML", de: "Format and validate XML" } },
];

export const getToolsByCategory = (category: Tool["category"]) =>
  tools.filter((t) => t.category === category);

export const getToolBySlug = (slug: string) =>
  tools.find((t) => t.slug === slug);
